"""Python <-> JavaScript parity test for curve evaluation.

# Generated by Claude

The web editor ships a JavaScript port of `utils/math/curves.py` at
`host/controller_web_editor/web/src/lib/curves.js` (plain ESM with JSDoc
types).  This test runs the JS module under Node and compares its output
against the Python implementation point-by-point on a dense input grid.

Skipped if `node` is not on PATH.  Robot CI runs Python only, but every
local developer has Node available from the Vite toolchain.
"""

import json
import os
import shutil
import subprocess
import sys
import textwrap

import pytest


_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


from utils.math.curves import (  # noqa: E402
    default_segment_points,
    default_spline_points,
    evaluate_segments,
    evaluate_spline,
)


_CURVES_JS = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "web", "src", "lib", "curves.js",
)).replace("\\", "/")


_SPLINE_FIXTURES = {
    "default_spline": default_spline_points(),
    "ramp_spline": [
        {"x": -1.0, "y": -1.0, "tangent": 0.5},
        {"x": -0.25, "y": -0.05, "tangent": 0.2},
        {"x": 0.25, "y": 0.05, "tangent": 0.2},
        {"x": 1.0, "y": 1.0, "tangent": 0.5},
    ],
    "steep_spline": [
        {"x": -1.0, "y": -1.0, "tangent": 2.5},
        {"x": 0.0, "y": 0.0, "tangent": 0.1},
        {"x": 1.0, "y": 1.0, "tangent": 2.5},
    ],
}

_SEGMENT_FIXTURES = {
    "default_segment": default_segment_points(),
    "deadzone_segment": [
        {"x": -1.0, "y": -1.0},
        {"x": -0.1, "y": 0.0},
        {"x": 0.1, "y": 0.0},
        {"x": 1.0, "y": 1.0},
    ],
    "shifted_segment": [
        {"x": -1.0, "y": -0.5},
        {"x": 0.2, "y": 0.1},
        {"x": 1.0, "y": 0.9},
    ],
}


def _input_grid() -> list[float]:
    # 41 samples across a slightly oversized range so we also test clamping.
    return [-1.2 + i * 0.06 for i in range(41)]


def _node_available() -> bool:
    return shutil.which("node") is not None


def _run_node(spline_fx: dict, segment_fx: dict, xs: list[float]) -> dict:
    """Import curves.js under Node and evaluate the fixtures."""
    driver = textwrap.dedent(f"""
        import {{ evaluateSpline, evaluateSegments }} from 'file://{_CURVES_JS}';
        const splineFx = {json.dumps(spline_fx)};
        const segFx = {json.dumps(segment_fx)};
        const xs = {json.dumps(xs)};
        const out = {{ spline: {{}}, segment: {{}} }};
        for (const k of Object.keys(splineFx)) {{
          out.spline[k] = xs.map((x) => evaluateSpline(splineFx[k], x));
        }}
        for (const k of Object.keys(segFx)) {{
          out.segment[k] = xs.map((x) => evaluateSegments(segFx[k], x));
        }}
        process.stdout.write(JSON.stringify(out));
    """)
    result = subprocess.run(
        ["node", "--input-type=module", "-e", driver],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"node driver failed (exit {result.returncode}):\n"
            f"stdout={result.stdout}\nstderr={result.stderr}")
    return json.loads(result.stdout)


@pytest.mark.skipif(not _node_available(), reason="node not installed")
def test_spline_parity():
    xs = _input_grid()
    ts_out = _run_node(_SPLINE_FIXTURES, _SEGMENT_FIXTURES, xs)
    for name, points in _SPLINE_FIXTURES.items():
        py_values = [evaluate_spline(points, x) for x in xs]
        js_values = ts_out["spline"][name]
        for x, py, js in zip(xs, py_values, js_values):
            assert py == pytest.approx(js, abs=1e-12), (
                f"{name} mismatch at x={x}: py={py} js={js}")


@pytest.mark.skipif(not _node_available(), reason="node not installed")
def test_segment_parity():
    xs = _input_grid()
    ts_out = _run_node(_SPLINE_FIXTURES, _SEGMENT_FIXTURES, xs)
    for name, points in _SEGMENT_FIXTURES.items():
        py_values = [evaluate_segments(points, x) for x in xs]
        js_values = ts_out["segment"][name]
        for x, py, js in zip(xs, py_values, js_values):
            assert py == pytest.approx(js, abs=1e-12), (
                f"{name} mismatch at x={x}: py={py} js={js}")
