"""Round-trip tests for the JSON <-> FullConfig conversion.

# Generated by Claude

Confirms the web editor can load any of the committed YAML configs and
serialize them back without losing information.  Also exercises the
path allowlist to catch traversal mistakes early.
"""

import os
import sys

import pytest


# Make ``host.controller_web_editor`` importable when pytest is run from any cwd.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


from host.controller_web_editor.paths import (  # noqa: E402
    PathNotAllowedError,
    list_yaml_configs,
    safe_resolve,
)
from host.controller_web_editor.routes.config import (  # noqa: E402
    config_from_json,
    config_to_json,
    load_as_json,
    save_from_json,
)
from utils.controller.config_io import load_config  # noqa: E402


_DATA_INPUTS = os.path.join(_REPO_ROOT, "data", "inputs")


def _config_paths() -> list[str]:
    return [
        os.path.join(_DATA_INPUTS, name)
        for name in os.listdir(_DATA_INPUTS)
        if name.endswith(".yaml")
    ]


class TestPathAllowlist:
    def test_allows_data_paths(self):
        resolved = safe_resolve("data/inputs/controller.yaml")
        assert resolved.is_file()

    def test_rejects_outside_paths(self):
        with pytest.raises(PathNotAllowedError):
            safe_resolve("pyproject.toml")

    def test_rejects_traversal(self):
        with pytest.raises(PathNotAllowedError):
            safe_resolve("data/../pyproject.toml")

    def test_rejects_empty(self):
        with pytest.raises(PathNotAllowedError):
            safe_resolve("")

    def test_list_includes_controller_yaml(self):
        configs = list_yaml_configs()
        assert "data/inputs/controller.yaml" in configs


class TestJsonRoundtrip:
    @pytest.mark.parametrize("path", _config_paths())
    def test_load_returns_jsonable(self, path):
        payload = load_as_json(path)
        # All values must survive json.dumps without a custom encoder.
        import json
        json.dumps(payload)
        assert payload["version"]
        assert isinstance(payload["actions"], dict)
        assert isinstance(payload["controllers"], dict)

    @pytest.mark.parametrize("path", _config_paths())
    def test_roundtrip_preserves_actions(self, path):
        original = load_config(path)
        payload = config_to_json(original)
        rebuilt = config_from_json(payload)

        assert set(rebuilt.actions) == set(original.actions)
        for qname, action in original.actions.items():
            other = rebuilt.actions[qname]
            assert other.input_type == action.input_type
            assert other.trigger_mode == action.trigger_mode
            assert other.description == action.description
            assert other.group == action.group
            assert other.deadband == action.deadband
            assert other.threshold == action.threshold
            assert other.inversion == action.inversion
            assert other.slew_rate == action.slew_rate
            assert other.scale == action.scale
            assert other.extra == action.extra

    @pytest.mark.parametrize("path", _config_paths())
    def test_roundtrip_preserves_controllers(self, path):
        original = load_config(path)
        rebuilt = config_from_json(config_to_json(original))
        assert set(rebuilt.controllers) == set(original.controllers)
        for port, ctrl in original.controllers.items():
            other = rebuilt.controllers[port]
            assert other.name == ctrl.name
            assert other.controller_type == ctrl.controller_type
            assert other.bindings == ctrl.bindings

    def test_save_then_load_matches(self, tmp_path):
        src = os.path.join(_DATA_INPUTS, "controller.yaml")
        payload = load_as_json(src)
        dst = tmp_path / "out.yaml"
        save_from_json(dst, payload)
        reloaded = load_as_json(dst)
        # Compare the substantive fields; version comes from CONFIG_VERSION
        # either way so equality is safe.
        assert reloaded["actions"] == payload["actions"]
        assert reloaded["controllers"] == payload["controllers"]
        assert set(reloaded["empty_groups"]) == set(payload["empty_groups"])
