"""Tests for the PNG/PDF export endpoint.

# Generated by Claude

The renderer itself lives in ``host/controller_config/print_render.py``;
these tests cover the web-side wiring: parameter validation, the path
allowlist, and that the returned bytes have the correct file signature
and MIME type.  Rendering quality is exercised by the Tkinter tool.
"""

import os
import sys

import pytest


_REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


from host.controller_web_editor.paths import safe_resolve  # noqa: E402
from host.controller_web_editor.routes.export import (  # noqa: E402
    ExportRequestError,
    export_from_yaml,
)

# Skip the whole module when the renderer's optional native deps aren't
# available (cairosvg → libcairo).  These tests only assert wiring, not
# the Tkinter tool's existing rendering coverage.
PIL = pytest.importorskip("PIL")
pytest.importorskip("yaml")


_DATA_INPUTS = os.path.join(_REPO_ROOT, "data", "inputs")
_CONFIG = os.path.join(_DATA_INPUTS, "controller.yaml")


PNG_SIG = b"\x89PNG\r\n\x1a\n"
PDF_SIG = b"%PDF-"


@pytest.fixture(scope="module")
def yaml_path():
    if not os.path.isfile(_CONFIG):
        pytest.skip(f"sample config not found: {_CONFIG}")
    return safe_resolve("data/inputs/controller.yaml")


@pytest.fixture
def single_controller_yaml(tmp_path):
    """Sample YAML trimmed to one controller — landscape PNG requires
    one page, so multi-controller fixtures can't be used for that case.
    """
    from utils.controller.config_io import load_config, save_config

    full = load_config(_CONFIG)
    # Keep only the first controller; drop the rest.
    ports = sorted(full.controllers.keys())
    if len(ports) > 1:
        for p in ports[1:]:
            del full.controllers[p]
    dst = tmp_path / "single.yaml"
    save_config(full, dst)
    return dst


class TestParameterValidation:
    def test_rejects_unknown_orientation(self, yaml_path):
        with pytest.raises(ExportRequestError):
            export_from_yaml(yaml_path, "sideways", "pdf")

    def test_rejects_unknown_format(self, yaml_path):
        with pytest.raises(ExportRequestError):
            export_from_yaml(yaml_path, "landscape", "gif")

    def test_format_normalizes_dot_prefix(self, yaml_path):
        # "format=.pdf" sometimes appears in query strings; renderer
        # should strip the leading dot.
        data, mime, _ = export_from_yaml(yaml_path, "landscape", ".pdf")
        assert mime == "application/pdf"
        assert data.startswith(PDF_SIG)


class TestRenderBytes:
    def test_landscape_pdf(self, yaml_path):
        data, mime, name = export_from_yaml(
            yaml_path, "landscape", "pdf", hide_unassigned=False)
        assert mime == "application/pdf"
        assert data.startswith(PDF_SIG)
        assert name.endswith("_landscape.pdf")
        assert len(data) > 1000  # sanity: PDFs aren't tiny

    def test_landscape_png_single_controller(self, single_controller_yaml):
        # PNG only works with a single page (one controller in landscape,
        # up to two in portrait), so use the trimmed fixture.
        data, mime, name = export_from_yaml(
            single_controller_yaml, "landscape", "png",
            hide_unassigned=False)
        assert mime == "image/png"
        assert data.startswith(PNG_SIG)
        assert name.endswith("_landscape.png")

    def test_landscape_png_rejects_multi_controller(self, yaml_path):
        # Sample config has two controllers; landscape PNG can't fit
        # both on a single page.  Renderer should raise so the client
        # gets a clear 400 instead of a truncated file.
        with pytest.raises(ValueError, match="single page"):
            export_from_yaml(yaml_path, "landscape", "png")

    def test_portrait_pdf(self, yaml_path):
        data, mime, _ = export_from_yaml(
            yaml_path, "portrait", "pdf", hide_unassigned=True)
        assert mime == "application/pdf"
        assert data.startswith(PDF_SIG)

    def test_filename_uses_yaml_stem(self, yaml_path):
        _, _, name = export_from_yaml(yaml_path, "landscape", "pdf")
        assert name.startswith("controller_")  # from controller.yaml
