"""Round-trip + safety tests for the hitbox layout route.

# Generated by Claude

Verifies the layout file loads cleanly, the layout allowlist rejects
unknown names, and save_layout writes a recoverable .bak.
"""

import json
import os
import sys

import pytest


_REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


from host.controller_web_editor.routes.hitboxes import (  # noqa: E402
    HITBOXES_DIR,
    LayoutNotAllowedError,
    list_layouts,
    load_layout,
    save_layout,
)


class TestLoad:
    def test_xbox_layout_loads(self):
        data = load_layout("xbox")
        assert data["viewBox"] == "0 0 744 500"
        assert isinstance(data["regions"], dict)
        # Spot-check that the canonical xbox inputs are present.
        assert "a_button" in data["regions"]
        assert "left_trigger" in data["regions"]
        assert "pov_up" in data["regions"]

    def test_rejects_unknown_layout(self):
        with pytest.raises(LayoutNotAllowedError):
            load_layout("ps5")

    def test_rejects_traversal(self):
        with pytest.raises(LayoutNotAllowedError):
            load_layout("../paths")

    def test_list_layouts_contains_xbox(self):
        assert "xbox" in list_layouts()


class TestSave:
    @pytest.fixture
    def restore_xbox(self):
        # Snapshot the file so the test can restore it regardless of outcome.
        src = HITBOXES_DIR / "xbox.json"
        snapshot = src.read_bytes()
        yield
        src.write_bytes(snapshot)
        bak = src.with_suffix(src.suffix + ".bak")
        if bak.exists():
            bak.unlink()

    def test_save_writes_file_and_bak(self, restore_xbox):
        original = load_layout("xbox")
        # Tweak one field so we can confirm the write took.
        modified = json.loads(json.dumps(original))
        modified["regions"]["a_button"] = {
            "shape": "circle", "cx": 999, "cy": 999, "r": 17,
        }
        save_layout("xbox", modified)

        reloaded = load_layout("xbox")
        assert reloaded["regions"]["a_button"]["cx"] == 999

        bak = HITBOXES_DIR / "xbox.json.bak"
        assert bak.is_file()
        assert json.loads(bak.read_text())["regions"]["a_button"]["cx"] == \
            original["regions"]["a_button"]["cx"]

    def test_save_rejects_unknown_layout(self):
        with pytest.raises(LayoutNotAllowedError):
            save_layout("ps5", {"viewBox": "0 0 1 1", "regions": {}})

    def test_save_rejects_missing_regions(self, restore_xbox):
        with pytest.raises(ValueError):
            save_layout("xbox", {"viewBox": "0 0 1 1"})

    def test_save_rejects_missing_viewbox(self, restore_xbox):
        with pytest.raises(ValueError):
            save_layout("xbox", {"regions": {}})

    def test_save_rejects_non_dict(self, restore_xbox):
        with pytest.raises(ValueError):
            save_layout("xbox", ["not", "a", "dict"])  # type: ignore[arg-type]

    def test_save_accepts_optional_labels_and_fonts(self, restore_xbox):
        original = load_layout("xbox")
        payload = json.loads(json.dumps(original))
        payload["labels"] = {"a_button": {"dx": 4.5, "dy": -22.0}}
        payload["fonts"] = {"input_name": 8, "action_label": 12}
        save_layout("xbox", payload)
        reloaded = load_layout("xbox")
        assert reloaded["labels"]["a_button"]["dy"] == -22.0
        assert reloaded["fonts"]["action_label"] == 12

    def test_save_rejects_non_dict_labels(self, restore_xbox):
        original = load_layout("xbox")
        payload = json.loads(json.dumps(original))
        payload["labels"] = "not a dict"
        with pytest.raises(ValueError):
            save_layout("xbox", payload)

    def test_save_rejects_non_dict_fonts(self, restore_xbox):
        original = load_layout("xbox")
        payload = json.loads(json.dumps(original))
        payload["fonts"] = 12
        with pytest.raises(ValueError):
            save_layout("xbox", payload)
