"""Controller Maps

Auto-generated by ``doc/build_docs.py``. Do not edit manually.

Each controller configuration in ``data/inputs/`` is rendered as a
landscape map image below.

## 2026Bot

![2026Bot Controller Map](./assets/2026bot_controller_map_page1.png)

![2026Bot Controller Map](./assets/2026bot_controller_map_page2.png)

## Controller

![Controller Controller Map](./assets/controller_controller_map_page1.png)

![Controller Controller Map](./assets/controller_controller_map_page2.png)

## General Unit Test Mappings

![General Unit Test Mappings Controller Map](./assets/general_unit_test_mappings_controller_map_page1.png)

![General Unit Test Mappings Controller Map](./assets/general_unit_test_mappings_controller_map_page2.png)
"""
