"""
Unit tests for IntakeSubsystem.
Generated by Claude.

Tests validate:
- Subsystem creation (default configuration)
- Roller activation/deactivation sets rollerCondition correctly
- updateRoller changes velocity
- motorChecks applies rollerCondition * rollerVelocity to the motor
- Jam detection triggers when velocity stays below threshold
- periodic() runs without error
- updateTelemetry() publishes encoder data to ntproperty
- Registry self-registration exists
"""

import pytest
import rev
import wpilib
import wpilib.simulation
from wpimath.system.plant import DCMotor

from constants import CaptainPlanetConsts as intakeConsts
from subsystem.intakeactions import IntakeSubsystem


# Module-scoped: SparkMax CAN IDs can only be instantiated once per process
@pytest.fixture(scope="module")
def intake():
    wpilib.simulation.pauseTiming()
    sub = IntakeSubsystem()
    yield sub
    wpilib.simulation.resumeTiming()


@pytest.fixture(scope="module")
def roller_sim(intake):
    return rev.SparkSim(intake.rollerMotor, DCMotor.NEO())


@pytest.fixture(scope="module")
def roller_enc_sim(roller_sim):
    return roller_sim.getRelativeEncoderSim()


@pytest.fixture(autouse=True)
def _reset_state(intake):
    """Reset intake state before each test."""
    intake.rollerCondition = 0
    intake.rollerVelocity = 0
    intake.jamDetected = False
    intake.jamOccurence = 0
    intake.baselineJam = 0
    intake.baselineDetectedJam = 0
    intake.rollerSensor = 0


# ---- Construction ----

def test_default_construction(intake):
    """Default config creates a SparkMax roller motor."""
    assert isinstance(intake.rollerMotor, rev.SparkMax)
    assert intake.rollerCondition == 0
    assert intake.rollerVelocity == 0
    assert intake.jamDetected is False


def test_can_ids_are_placeholders():
    """CAN IDs should be the placeholder values (40, 41)."""
    assert intakeConsts.kIntakeMotorCanId == 40
    assert intakeConsts.kRollerMotorCanId == 41


# ---- Roller activation ----

def test_activate_roller(intake):
    """activateRoller sets rollerCondition to 1."""
    assert intake.rollerCondition == 0
    intake.activateRoller()
    assert intake.rollerCondition == 1


def test_activate_roller_idempotent(intake):
    """Calling activateRoller twice keeps rollerCondition at 1."""
    intake.activateRoller()
    intake.activateRoller()
    assert intake.rollerCondition == 1


def test_deactivate_roller(intake):
    """deactivateRoller sets rollerCondition to 0."""
    intake.activateRoller()
    assert intake.rollerCondition == 1
    intake.deactivateRoller()
    assert intake.rollerCondition == 0


def test_deactivate_roller_idempotent(intake):
    """Calling deactivateRoller when already 0 is a no-op."""
    intake.deactivateRoller()
    assert intake.rollerCondition == 0


# ---- Velocity ----

def test_update_roller_velocity(intake):
    """updateRoller sets the roller velocity."""
    intake.updateRoller(0.5)
    assert intake.rollerVelocity == 0.5


def test_motor_checks_applies_velocity(intake):
    """motorChecks sets motor output to rollerCondition * rollerVelocity."""
    intake.rollerVelocity = 0.3
    intake.rollerCondition = 1
    intake.motorChecks()
    assert intake.rollerMotor.get() == pytest.approx(0.3)


def test_motor_checks_zero_when_deactivated(intake):
    """motorChecks sets motor output to 0 when rollerCondition is 0."""
    intake.rollerVelocity = 0.5
    intake.rollerCondition = 0
    intake.motorChecks()
    assert intake.rollerMotor.get() == pytest.approx(0.0)


def test_motor_checks_reverse(intake):
    """motorChecks applies negative output when rollerCondition is -1."""
    intake.rollerVelocity = 0.4
    intake.rollerCondition = -1
    intake.motorChecks()
    assert intake.rollerMotor.get() == pytest.approx(-0.4)


# ---- Jam detection ----

def test_jam_not_detected_when_roller_inactive(intake, roller_enc_sim):
    """No jam detected when rollerCondition is 0 (roller off)."""
    intake.rollerCondition = 0
    roller_enc_sim.setVelocity(0)
    intake.jamDetection()
    assert intake.jamDetected is False
    assert intake.jamOccurence == 0


def test_jam_detection_starts_timer_on_low_velocity(intake, roller_enc_sim):
    """When roller is active and velocity is below threshold, jamOccurence starts."""
    intake.rollerCondition = 1
    roller_enc_sim.setVelocity(0)
    intake.jamDetection()
    assert intake.jamOccurence == 1
    assert intake.jamDetected is False


def test_jam_not_detected_above_threshold(intake, roller_enc_sim):
    """No jam when roller velocity is above jamThreshold."""
    intake.rollerCondition = 1
    roller_enc_sim.setVelocity(intake.jamThreshold + 100)
    intake.jamDetection()
    assert intake.jamOccurence == 0
    assert intake.jamDetected is False


# ---- Periodic ----

def test_periodic_runs_without_error(intake):
    """periodic() should not raise any exceptions."""
    intake.periodic()


# ---- Telemetry ----

def test_update_telemetry_publishes_position(intake, roller_enc_sim):
    """updateTelemetry() writes encoder position to ntproperty."""
    roller_enc_sim.setPosition(42.0)
    intake.updateTelemetry()
    assert intake.rollerPosition == pytest.approx(42.0)


def test_update_telemetry_publishes_velocity(intake, roller_enc_sim):
    """updateTelemetry() writes encoder velocity to ntproperty."""
    roller_enc_sim.setVelocity(500.0)
    intake.updateTelemetry()
    assert intake.rollerEncoderVelocity == pytest.approx(500.0)


# ---- Registry ----

def test_registry_registration():
    """IntakeSubsystem should be self-registered with the subsystem registry."""
    from utils.subsystem_factory import get_registered_entries
    names = [e.name for e in get_registered_entries()]
    assert "intake" in names
