"""Regression tests for PhysicsEngine initialization.
# Generated by Claude

Covers the failure mode where CANcoder sim devices return stale/no data on
some platforms (observed on macOS with Python 3.13), causing SwerveDrivetrain
to fall back to swerve_modules=[] and then crashing in update_sim with:

    TypeError: toChassisSpeeds(): incompatible function arguments
    Invoked with: <SwerveDrive4Kinematics ...>, ()

The fix is a fast-fail in PhysicsEngine.__init__ that raises a clear RuntimeError
instead of allowing the confusing TypeError to surface later in update_sim.
"""

import types
import pytest
import hal


def setup_module():
    hal.initialize(500, 0)


def _make_mock_robot(num_modules: int):
    """Build a minimal mock robot with the given number of swerve modules."""
    robot = types.SimpleNamespace()
    robot.container = types.SimpleNamespace()
    robot.container.drivetrain = types.SimpleNamespace()
    robot.container.drivetrain.swerve_modules = [object()] * num_modules
    return robot


class TestPhysicsEngineInit:
    def test_raises_when_no_modules(self):
        """Simulates CANcoder init failure — all 4 modules fail, list is empty."""
        from physics import PhysicsEngine
        robot = _make_mock_robot(0)
        with pytest.raises(RuntimeError, match="4 swerve modules"):
            PhysicsEngine.__new__(PhysicsEngine).__init__(None, robot)

    def test_raises_when_partial_modules(self):
        """Simulates partial CANcoder failure — only some modules created."""
        from physics import PhysicsEngine
        robot = _make_mock_robot(2)
        with pytest.raises(RuntimeError, match="4 swerve modules"):
            PhysicsEngine.__new__(PhysicsEngine).__init__(None, robot)
