"""
Unit tests for the Hood subsystem.

Tests validate:
- Setpoint clamping (degrees, normalized, radians)
- Conversion accuracy between units
- Soft limit configuration
- Encoder conversion factor
- Brake mode configuration
- Mechanism2d creation
- Telemetry output
- atSetpoint logic
- periodic() drives motor voltage

Generated by Claude.
"""

# Native imports
import math
import unittest

# Third-party imports
import rev
import wpilib
import wpilib.simulation
from wpimath.system.plant import DCMotor

# Internal imports
from subsystem.mechanisms.shooter.hood import Hood


class TestHood(unittest.TestCase):
    """Test suite for the Hood subsystem.

    Uses setUpClass/tearDownClass to create a single SparkMax instance
    shared across all tests, since REV enforces one instance per CAN ID.
    """

    MOTOR_CAN_ID = 34
    POSITION_CONVERSION_FACTOR = 360.0 / 1.7  # degrees per motor rotation
    MAX_ANGLE_DEGREES = 30.0
    PID = (0.5, 0, 0)
    FEEDFORWARD = (0, 0, 0, 0)

    @classmethod
    def setUpClass(cls):
        """Create motor, hood, and simulation objects once for all tests."""
        wpilib.simulation.pauseTiming()
        cls.motor = rev.SparkMax(
            cls.MOTOR_CAN_ID,
            rev.SparkLowLevel.MotorType.kBrushless
        )
        cls.hood = Hood(
            motor=cls.motor,
            position_conversion_factor=cls.POSITION_CONVERSION_FACTOR,
            max_angle_degrees=cls.MAX_ANGLE_DEGREES,
            pid=cls.PID,
            feedforward=cls.FEEDFORWARD,
        )
        cls.motor_sim = rev.SparkSim(cls.motor, DCMotor.NEO())
        cls.motor_sim.setBusVoltage(12.0)

    def setUp(self):
        """Reset hood state before each test."""
        self.hood._target_degrees = 0.0
        self.motor_sim.getRelativeEncoderSim().setPosition(0.0)
        self.motor.stopMotor()

    # -- Setpoint degrees --

    def test_set_angle_degrees(self):
        self.hood.setAngleDegrees(15.0)
        assert self.hood._target_degrees == 15.0

    def test_set_angle_degrees_clamps_above_max(self):
        self.hood.setAngleDegrees(45.0)
        assert self.hood._target_degrees == self.MAX_ANGLE_DEGREES

    def test_set_angle_degrees_clamps_below_min(self):
        self.hood.setAngleDegrees(-5.0)
        assert self.hood._target_degrees == 0.0

    # -- Setpoint normalized --

    def test_set_angle_normalized_zero(self):
        self.hood.setAngleNormalized(0.0)
        assert self.hood._target_degrees == 0.0

    def test_set_angle_normalized_one(self):
        self.hood.setAngleNormalized(1.0)
        assert self.hood._target_degrees == self.MAX_ANGLE_DEGREES

    def test_set_angle_normalized_half(self):
        self.hood.setAngleNormalized(0.5)
        assert self.hood._target_degrees == self.MAX_ANGLE_DEGREES / 2.0

    def test_set_angle_normalized_clamps_above(self):
        self.hood.setAngleNormalized(1.5)
        assert self.hood._target_degrees == self.MAX_ANGLE_DEGREES

    def test_set_angle_normalized_clamps_below(self):
        self.hood.setAngleNormalized(-0.5)
        assert self.hood._target_degrees == 0.0

    # -- Setpoint radians --

    def test_set_angle_radians(self):
        self.hood.setAngleRadians(math.radians(20.0))
        assert abs(self.hood._target_degrees - 20.0) < 0.01

    def test_set_angle_radians_clamps(self):
        self.hood.setAngleRadians(math.radians(50.0))
        assert self.hood._target_degrees == self.MAX_ANGLE_DEGREES

    # -- Getters --

    def test_get_angle_degrees(self):
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        assert abs(self.hood.getAngleDegrees() - 10.0) < 0.01

    def test_get_angle_normalized(self):
        self.motor_sim.getRelativeEncoderSim().setPosition(15.0)
        expected = 15.0 / self.MAX_ANGLE_DEGREES
        assert abs(self.hood.getAngleNormalized() - expected) < 0.01

    def test_get_angle_radians(self):
        self.motor_sim.getRelativeEncoderSim().setPosition(20.0)
        expected = math.radians(20.0)
        assert abs(self.hood.getAngleRadians() - expected) < 0.01

    def test_get_target_degrees(self):
        self.hood.setAngleDegrees(12.0)
        assert self.hood.getTargetDegrees() == 12.0

    # -- atSetpoint --

    def test_at_setpoint_true(self):
        self.hood.setAngleDegrees(10.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.hood.periodic()
        assert self.hood.atSetpoint()

    def test_at_setpoint_false(self):
        self.hood.setAngleDegrees(10.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(5.0)
        self.hood.periodic()
        assert not self.hood.atSetpoint()

    def test_at_setpoint_within_tolerance(self):
        self.hood.controller.setTolerance(0.5)
        self.hood.setAngleDegrees(10.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(10.3)
        self.hood.periodic()
        assert self.hood.atSetpoint()

    # -- Configuration --

    def test_soft_limits_configured(self):
        sl = self.motor.configAccessor.softLimit
        assert sl.getForwardSoftLimit() == self.MAX_ANGLE_DEGREES
        assert sl.getReverseSoftLimit() == 0.0

    def test_encoder_conversion_factor(self):
        enc_config = self.motor.configAccessor.encoder
        assert abs(
            enc_config.getPositionConversionFactor()
            - self.POSITION_CONVERSION_FACTOR
        ) < 0.01

    def test_idle_mode_is_brake(self):
        assert (
            self.motor.configAccessor.getIdleMode()
            == rev.SparkBaseConfig.IdleMode.kBrake
        )

    # -- Mechanism2d --

    def test_mechanism2d_exists(self):
        assert self.hood.mech2d is not None
        assert self.hood.mech_current_arm is not None
        assert self.hood.mech_target_arm is not None

    # -- Telemetry --

    def test_telemetry_runs_without_error(self):
        self.hood.setAngleDegrees(15.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.hood.updateTelemetry()

    # -- Periodic --

    def test_periodic_runs_without_error(self):
        self.hood.setAngleDegrees(15.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.hood.periodic()

    # -- Disable --

    def test_disable(self):
        self.hood.setAngleDegrees(15.0)
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.hood.disable()
        assert abs(self.hood._target_degrees - 10.0) < 0.01

    # -- Horizontal offset --

    def test_horizontal_offset_default(self):
        assert self.hood._horizontal_offset_degrees == 0.0
