"""
Tests for loop timing instrumentation.
# Generated by Claude
"""

import math

import hal
import pytest
import wpilib

from utils.loop_timing import LoopTimingStats, LoopTimer


@pytest.fixture
def wpilib_sim():
    """Initialize HAL in sim mode so FPGA timestamps and SmartDashboard work."""
    hal.initialize(500, 0)
    yield


# ---------------------------------------------------------------------------
# LoopTimingStats — pure math, no WPILib needed
# ---------------------------------------------------------------------------

class TestLoopTimingStats:

    def test_initial_state(self):
        s = LoopTimingStats()
        assert s.count == 0
        assert s.min_ms == 0.0
        assert s.max_ms == 0.0
        assert s.avg_ms == 0.0
        assert s.stddev_ms == 0.0
        assert s.last_ms == 0.0

    def test_single_sample(self):
        s = LoopTimingStats()
        s.record(0.005)  # 5 ms
        assert s.count == 1
        assert s.last_ms == 5.0
        assert s.min_ms == 5.0
        assert s.max_ms == 5.0
        assert s.avg_ms == 5.0
        assert s.stddev_ms == 0.0  # need >=2 samples

    def test_known_values(self):
        """Record [2, 4, 4, 4, 5, 5, 7, 9] ms — known mean=5, stddev~2."""
        s = LoopTimingStats()
        values_ms = [2, 4, 4, 4, 5, 5, 7, 9]
        for v in values_ms:
            s.record(v / 1000.0)  # input in seconds

        assert s.count == 8
        assert s.min_ms == 2.0
        assert s.max_ms == 9.0
        assert s.avg_ms == 5.0
        assert s.last_ms == 9.0
        # Population variance=4, sample variance=4.571..., sample stddev~2.138
        assert abs(s.stddev_ms - 2.138) < 0.01

    def test_reset(self):
        s = LoopTimingStats()
        s.record(0.010)
        s.record(0.020)
        s.reset()
        assert s.count == 0
        assert s.min_ms == 0.0
        assert s.max_ms == 0.0
        assert s.avg_ms == 0.0
        assert s.stddev_ms == 0.0
        assert s.last_ms == 0.0

    def test_last_ms_tracks_most_recent(self):
        s = LoopTimingStats()
        s.record(0.001)
        assert s.last_ms == 1.0
        s.record(0.007)
        assert s.last_ms == 7.0
        s.record(0.003)
        assert s.last_ms == 3.0

    def test_two_samples_stddev(self):
        s = LoopTimingStats()
        s.record(0.002)  # 2 ms
        s.record(0.006)  # 6 ms
        # mean=4, sample variance = ((2-4)^2 + (6-4)^2) / 1 = 8
        # sample stddev = sqrt(8) ~ 2.828
        assert abs(s.stddev_ms - math.sqrt(8)) < 0.001


# ---------------------------------------------------------------------------
# LoopTimer — needs WPILib sim for FPGA timestamps + SmartDashboard
# ---------------------------------------------------------------------------

class TestLoopTimer:

    def test_start_stop_records_duration(self, wpilib_sim):
        """start/stop should record a non-negative duration."""
        lt = LoopTimer(budget_sec=0.020)
        lt.add_channel("test")
        lt.start("test")
        # In sim, FPGA time doesn't advance between calls, so duration ~ 0.
        lt.stop("test")
        assert lt._channels["test"].count == 1
        assert lt._channels["test"].last_ms >= 0.0

    def test_reset_clears_channels(self, wpilib_sim):
        lt = LoopTimer(budget_sec=0.020)
        lt.add_channel("a")
        lt.add_channel("b")
        lt.start("a")
        lt.stop("a")
        lt.start("b")
        lt.stop("b")
        assert lt._channels["a"].count == 1
        assert lt._channels["b"].count == 1
        lt.reset_all()
        assert lt._channels["a"].count == 0
        assert lt._channels["b"].count == 0

    def test_publish_writes_smartdashboard(self, wpilib_sim):
        lt = LoopTimer(budget_sec=0.020)
        lt.add_channel("ch")
        lt.start("ch")
        lt.stop("ch")
        lt.publish()

        # Verify keys were written
        assert wpilib.SmartDashboard.containsKey("FrameTiming/ch/lastMs")
        assert wpilib.SmartDashboard.containsKey("FrameTiming/ch/avgMs")
        assert wpilib.SmartDashboard.containsKey("FrameTiming/ch/budgetPct")
        assert wpilib.SmartDashboard.containsKey("FrameTiming/totalMs")
        assert wpilib.SmartDashboard.containsKey("FrameTiming/totalBudgetPct")

    def test_total_sums_channels(self, wpilib_sim):
        lt = LoopTimer(budget_sec=0.020)
        lt.add_channel("a")
        lt.add_channel("b")
        # Manually inject known durations
        lt._channels["a"].record(0.005)  # 5 ms
        lt._channels["b"].record(0.003)  # 3 ms
        lt.publish()

        total = wpilib.SmartDashboard.getNumber("FrameTiming/totalMs", -1)
        assert abs(total - 8.0) < 0.001
        pct = wpilib.SmartDashboard.getNumber("FrameTiming/totalBudgetPct", -1)
        assert abs(pct - 40.0) < 0.001  # 8ms / 20ms = 40%
