"""
Unit tests for the PositionCalibration utility class.
Generated by Claude.

Standalone tests covering homing, calibration, margin, persistence,
telemetry, and abort behavior. Uses CAN ID 41 to avoid conflict with
turret tests (CAN ID 40).
"""

# Native imports
import unittest

# Third-party imports
import rev
import wpilib
import wpilib.simulation
from wpimath.system.plant import DCMotor

# Internal imports
import ntcore
from utils.position_calibration import PositionCalibration, _calibration_classes


class TestPositionCalibration(unittest.TestCase):
    """Test suite for the PositionCalibration utility class."""

    MOTOR_CAN_ID = 41
    MIN_SOFT_LIMIT = -90.0
    MAX_SOFT_LIMIT = 90.0

    @classmethod
    def setUpClass(cls):
        """Create motor and simulation objects once for all tests."""
        wpilib.simulation.pauseTiming()
        cls.motor = rev.SparkMax(
            cls.MOTOR_CAN_ID,
            rev.SparkLowLevel.MotorType.kBrushless
        )
        # Configure encoder conversion factor
        config = rev.SparkMaxConfig()
        config.encoder.positionConversionFactor(3.6)
        config.encoder.velocityConversionFactor(3.6 / 60.0)
        (
            config.softLimit
            .forwardSoftLimit(cls.MAX_SOFT_LIMIT)
            .forwardSoftLimitEnabled(True)
            .reverseSoftLimit(cls.MIN_SOFT_LIMIT)
            .reverseSoftLimitEnabled(True)
        )
        config.smartCurrentLimit(40)
        cls.motor.configure(
            config,
            rev.ResetMode.kResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        cls.encoder = cls.motor.getEncoder()
        cls.motor_sim = rev.SparkSim(cls.motor, DCMotor.NEO())
        cls.motor_sim.setBusVoltage(12.0)

    def setUp(self):
        """Reset calibration state before each test."""
        # restartTiming() makes existing NT topic handles read-only,
        # so we must unpublish them, clear the ntproperty class cache,
        # and let PositionCalibration recreate fresh entries.
        wpilib.simulation.restartTiming()
        wpilib.simulation.pauseTiming()

        # Unpublish calibration topics so fresh entries can write
        inst = ntcore.NetworkTableInstance.getDefault()
        prefix = "/TestMech/calibration"
        for key in ["hard_limit_min", "hard_limit_max", "soft_limit_margin"]:
            inst.getEntry(f"{prefix}/{key}").unpublish()

        # Clear ntproperty class cache so entries are recreated
        _calibration_classes.pop("TestMech", None)

        self.cal = PositionCalibration(
            name="TestMech",
            motor=self.motor,
            encoder=self.encoder,
            default_min_soft_limit=self.MIN_SOFT_LIMIT,
            default_max_soft_limit=self.MAX_SOFT_LIMIT,
        )
        # Restore soft limits on motor
        limit_config = rev.SparkMaxConfig()
        (
            limit_config.softLimit
            .forwardSoftLimit(self.MAX_SOFT_LIMIT)
            .forwardSoftLimitEnabled(True)
            .reverseSoftLimit(self.MIN_SOFT_LIMIT)
            .reverseSoftLimitEnabled(True)
        )
        limit_config.smartCurrentLimit(40)
        self.motor.configure(
            limit_config,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        self.motor.stopMotor()

    # ---- Initial state tests ----

    def test_initial_state_not_busy(self):
        """Test that a new calibration is not busy."""
        self.assertFalse(self.cal.is_busy)

    def test_initial_state_not_calibrated(self):
        """Test that a new calibration is not calibrated."""
        self.assertFalse(self.cal.is_calibrated)
        self.assertFalse(self.cal.is_zeroed)

    def test_initial_soft_limits(self):
        """Test that initial soft limits match defaults."""
        self.assertEqual(self.cal.min_soft_limit, self.MIN_SOFT_LIMIT)
        self.assertEqual(self.cal.max_soft_limit, self.MAX_SOFT_LIMIT)

    def test_initial_hard_limits_none(self):
        """Test that hard limits are None before calibration."""
        self.assertIsNone(self.cal.min_limit)
        self.assertIsNone(self.cal.max_limit)

    # ---- Homing tests ----

    def test_homing_init_sets_busy(self):
        """Test that homing_init sets is_busy and is_homing."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertTrue(self.cal.is_busy)
        self.assertTrue(self.cal.is_homing)
        self.assertFalse(self.cal.is_calibrating)

    def test_homing_forward_drives_positive(self):
        """Test that forward homing drives motor with positive duty cycle."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.3,
            max_homing_time=5.0, homing_forward=True
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)
        self.cal._homing_periodic()
        self.assertAlmostEqual(self.motor.get(), 0.3, places=1)

    def test_homing_reverse_drives_negative(self):
        """Test that reverse homing drives motor with negative duty cycle."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.3,
            max_homing_time=5.0, homing_forward=False
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(-50.0)
        self.cal._homing_periodic()
        self.assertAlmostEqual(self.motor.get(), -0.3, places=1)

    def test_homing_stall_detection(self):
        """Test stall detection completes homing after 100ms."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        result = self.cal._homing_periodic()
        self.assertFalse(result)

        wpilib.simulation.stepTiming(0.15)

        result = self.cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(self.cal.is_homing)

    def test_homing_timeout(self):
        """Test that homing times out correctly."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=0.5,
            homing_forward=True,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)

        wpilib.simulation.stepTiming(0.6)

        result = self.cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(self.cal.is_homing)

    def test_homing_restores_settings(self):
        """Test that homing end restores motor settings."""
        original_current = self.motor.configAccessor.getSmartCurrentLimit()
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertAlmostEqual(
            self.motor.configAccessor.getSmartCurrentLimit(), 10.0, places=0)

        self.cal._homing_end(abort=False)

        self.assertAlmostEqual(
            self.motor.configAccessor.getSmartCurrentLimit(),
            original_current, places=0)
        self.assertTrue(
            self.motor.configAccessor.softLimit.getForwardSoftLimitEnabled())

    def test_homing_sets_encoder_forward(self):
        """Test encoder reset to max_soft_limit on forward homing complete."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)
        self.cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._homing_periodic()

        self.assertAlmostEqual(
            self.encoder.getPosition(), self.MAX_SOFT_LIMIT, places=1)

    def test_homing_sets_encoder_reverse(self):
        """Test encoder reset to min_soft_limit on reverse homing complete."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)
        self.cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._homing_periodic()

        self.assertAlmostEqual(
            self.encoder.getPosition(), self.MIN_SOFT_LIMIT, places=1)

    # ---- Calibration tests ----

    def test_calibration_init_sets_state(self):
        """Test that calibration_init sets flags and starts phase 1."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        self.assertTrue(self.cal.is_calibrating)
        self.assertTrue(self.cal.is_homing)
        self.assertTrue(self.cal.is_busy)
        self.assertEqual(self.cal._calibration_phase, 1)

    def test_calibration_full_two_phase(self):
        """Test complete two-phase calibration discovers full range."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # Phase 1: stall reverse
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal._calibration_phase, 2)

        # Phase 2: set position and stall forward
        encoder_sim.setPosition(180.0)
        encoder_sim.setVelocity(0.0)
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertFalse(self.cal.is_calibrating)
        self.assertTrue(self.cal.is_calibrated)
        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal.max_limit, 180.0)

    def test_calibration_known_range(self):
        """Test single-direction calibration with known range."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0,
            known_range=200.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # Phase 1 only
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertTrue(self.cal.is_calibrated)
        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal.max_limit, 200.0)

    def test_calibration_abort(self):
        """Test that abort clears calibration state."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        self.cal.abort()

        self.assertFalse(self.cal.is_busy)
        self.assertFalse(self.cal.is_calibrated)
        # Motor settings should be restored
        ca = self.motor.configAccessor
        self.assertTrue(ca.softLimit.getForwardSoftLimitEnabled())
        self.assertTrue(ca.softLimit.getReverseSoftLimitEnabled())

    def test_calibration_abort_during_homing(self):
        """Test that abort works when only homing is active."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.cal.abort()
        self.assertFalse(self.cal.is_busy)

    # ---- Soft limit margin tests ----

    def test_soft_limit_margin_default(self):
        """Test default soft limit margin is 5%."""
        self.assertAlmostEqual(self.cal.soft_limit_margin, 0.05)

    def test_set_soft_limit_margin_when_calibrated(self):
        """Test set_soft_limit_margin applies margins correctly."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 0.0
        self.cal._hard_limit_max = 200.0
        self.cal.set_soft_limit_margin(0.10)

        self.assertAlmostEqual(self.cal.min_soft_limit, 20.0, places=1)
        self.assertAlmostEqual(self.cal.max_soft_limit, 180.0, places=1)
        self.assertAlmostEqual(self.cal.soft_limit_margin, 0.10)

    def test_set_soft_limit_margin_applies_to_motor(self):
        """Test that set_soft_limit_margin updates motor controller."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 0.0
        self.cal._hard_limit_max = 100.0
        self.cal.set_soft_limit_margin(0.05)

        ca = self.motor.configAccessor
        self.assertTrue(ca.softLimit.getForwardSoftLimitEnabled())
        self.assertTrue(ca.softLimit.getReverseSoftLimitEnabled())
        self.assertAlmostEqual(
            ca.softLimit.getForwardSoftLimit(), 95.0, places=1)
        self.assertAlmostEqual(
            ca.softLimit.getReverseSoftLimit(), 5.0, places=1)

    def test_set_soft_limit_margin_noop_uncalibrated(self):
        """Test set_soft_limit_margin does nothing when uncalibrated."""
        original_min = self.cal.min_soft_limit
        original_max = self.cal.max_soft_limit
        self.cal.set_soft_limit_margin(0.10)
        self.assertEqual(self.cal.min_soft_limit, original_min)
        self.assertEqual(self.cal.max_soft_limit, original_max)

    # ---- Persistence tests ----

    def test_save_and_load_from_nt(self):
        """Test that calibration data persists via NT Preferences."""
        # Calibrate
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 5.0
        self.cal._hard_limit_max = 195.0
        self.cal._soft_limit_margin = 0.08
        self.cal._save_to_nt()

        # Create a new instance - should load persisted data
        cal2 = PositionCalibration(
            name="TestMech",
            motor=self.motor,
            encoder=self.encoder,
            default_min_soft_limit=self.MIN_SOFT_LIMIT,
            default_max_soft_limit=self.MAX_SOFT_LIMIT,
        )
        self.assertTrue(cal2.is_calibrated)
        self.assertEqual(cal2.min_limit, 5.0)
        self.assertEqual(cal2.max_limit, 195.0)
        self.assertAlmostEqual(cal2.soft_limit_margin, 0.08)

    def test_no_load_when_no_persisted_data(self):
        """Test that missing NT data doesn't mark as calibrated."""
        cal = PositionCalibration(
            name="NoData",
            motor=self.motor,
            encoder=self.encoder,
            default_min_soft_limit=-45.0,
            default_max_soft_limit=45.0,
        )
        self.assertFalse(cal.is_calibrated)
        self.assertIsNone(cal.min_limit)
        self.assertIsNone(cal.max_limit)

    # ---- Telemetry tests ----

    def test_update_telemetry_publishes_keys(self):
        """Test that update_telemetry publishes expected keys."""
        prefix = "TestMech/"
        self.cal.update_telemetry(prefix)
        sd = wpilib.SmartDashboard
        self.assertTrue(sd.containsKey(prefix + "isCalibrated"))
        self.assertTrue(sd.containsKey(prefix + "isCalibrating"))
        self.assertTrue(sd.containsKey(prefix + "isHoming"))
        self.assertTrue(sd.containsKey(prefix + "hardLimitMin"))
        self.assertTrue(sd.containsKey(prefix + "hardLimitMax"))
        self.assertTrue(sd.containsKey(prefix + "positionOffset"))
        self.assertTrue(sd.containsKey(prefix + "softLimitMargin"))

    def test_telemetry_reflects_state(self):
        """Test that telemetry values match internal state."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 10.0
        self.cal._hard_limit_max = 170.0
        prefix = "TestMech/"
        self.cal.update_telemetry(prefix)
        sd = wpilib.SmartDashboard
        self.assertTrue(sd.getBoolean(prefix + "isCalibrated", False))
        self.assertAlmostEqual(
            sd.getNumber(prefix + "hardLimitMin", 0.0), 10.0, places=1)
        self.assertAlmostEqual(
            sd.getNumber(prefix + "hardLimitMax", 0.0), 170.0, places=1)

    # ---- Periodic routing tests ----

    def test_periodic_routes_to_calibration(self):
        """Test that periodic() calls calibration state machine."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # periodic() should drive the calibration state machine
        self.cal.periodic()
        # Motor should be driven by homing (reverse direction)
        self.assertAlmostEqual(self.motor.get(), -0.2, places=1)

    def test_periodic_routes_to_homing(self):
        """Test that periodic() calls homing when only homing is active."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.25,
            max_homing_time=5.0, homing_forward=True
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)

        self.cal.periodic()
        self.assertAlmostEqual(self.motor.get(), 0.25, places=2)


if __name__ == "__main__":
    unittest.main()
