"""
Unit tests for the PassiveRangeFinderCommand.

Tests validate:
- Coast mode set on start, original idle mode restored on stop
- Conversion factor set to 1.0 during run, restored on stop
- Min/max tracking updates correctly
- Interrupted end restores idle mode without applying soft limits
- Normal end applies discovered range as soft limits

Generated by Claude.
"""

import unittest

import rev
import wpilib
import wpilib.simulation
from commands2 import Subsystem
from wpimath.system.plant import DCMotor

from utils.passive_range_finder import PassiveRangeFinderCommand


class TestPassiveRangeFinder(unittest.TestCase):
    """Test suite for PassiveRangeFinderCommand."""

    MOTOR_CAN_ID = 18
    POSITION_CONVERSION_FACTOR = 360.0 / 1.7

    @classmethod
    def setUpClass(cls):
        wpilib.simulation.pauseTiming()
        cls.motor = rev.SparkMax(
            cls.MOTOR_CAN_ID,
            rev.SparkLowLevel.MotorType.kBrushless
        )
        cls.subsystem = Subsystem()
        cls.motor_sim = rev.SparkSim(cls.motor, DCMotor.NEO())
        cls.motor_sim.setBusVoltage(12.0)

        # Configure motor with known settings
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kBrake)
        (
            cfg.encoder
            .positionConversionFactor(cls.POSITION_CONVERSION_FACTOR)
            .velocityConversionFactor(cls.POSITION_CONVERSION_FACTOR / 60.0)
        )
        cls.motor.configure(
            cfg,
            rev.ResetMode.kResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )

    def setUp(self):
        # Restore known config before each test
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kBrake)
        (
            cfg.encoder
            .positionConversionFactor(self.POSITION_CONVERSION_FACTOR)
            .velocityConversionFactor(self.POSITION_CONVERSION_FACTOR / 60.0)
        )
        self.motor.configure(
            cfg,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        self.motor_sim.getRelativeEncoderSim().setPosition(0.0)
        self.cmd = PassiveRangeFinderCommand(
            self.motor, "TestHood", self.subsystem)

    # -- Initialize tests --

    def test_initialize_sets_coast_mode(self):
        self.cmd.initialize()
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kCoast)
        self.cmd.end(True)

    def test_initialize_sets_conversion_factor_to_one(self):
        self.cmd.initialize()
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - 1.0) < 0.01
        self.cmd.end(True)

    def test_initialize_resets_min_max(self):
        self.motor_sim.getRelativeEncoderSim().setPosition(5.0)
        self.cmd.initialize()
        assert abs(self.cmd._min_raw - 5.0) < 0.01
        assert abs(self.cmd._max_raw - 5.0) < 0.01
        self.cmd.end(True)

    # -- Execute tests --

    def test_execute_tracks_max(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.cmd.execute()
        assert abs(self.cmd._max_raw - 10.0) < 0.01
        self.cmd.end(True)

    def test_execute_tracks_min(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(-3.0)
        self.cmd.execute()
        assert abs(self.cmd._min_raw - (-3.0)) < 0.01
        self.cmd.end(True)

    def test_execute_tracks_both(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(-5.0)
        self.cmd.execute()
        assert abs(self.cmd._max_raw - 10.0) < 0.01
        assert abs(self.cmd._min_raw - (-5.0)) < 0.01
        self.cmd.end(True)

    # -- End (normal) tests --

    def test_end_restores_conversion_factor(self):
        self.cmd.initialize()
        self.cmd.end(False)
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - self.POSITION_CONVERSION_FACTOR) < 0.01

    def test_end_restores_idle_mode(self):
        self.cmd.initialize()
        self.cmd.end(False)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kBrake)

    def test_end_applies_soft_limits(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(0.2)
        self.cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(-0.1)
        self.cmd.execute()
        self.cmd.end(False)

        sl = self.motor.configAccessor.softLimit
        assert sl.getForwardSoftLimitEnabled()
        assert sl.getReverseSoftLimitEnabled()
        # Soft limits should be scaled by original conversion factor
        expected_fwd = 0.2 * self.POSITION_CONVERSION_FACTOR
        expected_rev = -0.1 * self.POSITION_CONVERSION_FACTOR
        assert abs(sl.getForwardSoftLimit() - expected_fwd) < 0.1
        assert abs(sl.getReverseSoftLimit() - expected_rev) < 0.1

    # -- End (interrupted) tests --

    def test_interrupted_restores_idle_mode(self):
        self.cmd.initialize()
        self.cmd.end(True)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kBrake)

    def test_interrupted_restores_conversion_factor(self):
        self.cmd.initialize()
        self.cmd.end(True)
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - self.POSITION_CONVERSION_FACTOR) < 0.01

    # -- isFinished --

    def test_is_finished_returns_false(self):
        assert not self.cmd.isFinished()

    # -- Coast mode restore for originally coast motor --

    def test_coast_motor_stays_coast(self):
        """If motor was originally coast, it should stay coast after end."""
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kCoast)
        self.motor.configure(
            cfg,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        cmd = PassiveRangeFinderCommand(
            self.motor, "TestCoast", self.subsystem)
        cmd.initialize()
        cmd.end(False)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kCoast)
