"""
Unit tests for swerve module Mechanism2d visualization.
Generated by Claude.

Tests validate:
- set_state() stores correct commanded state after optimize()
- Mechanism2d commanded arm shows 0° (robot-frame) when driving forward
- Mechanism2d commanded arm shows 180° (robot-frame) when driving backward
- Mechanism2d commanded arm has maximum length at max speed

Background:
  optimize() flips states where the angle delta > 90° to use negative speed at the
  closer angle.  For backward motion from steer=0°:
    kinematics input : {speed=+max, angle=180°}
    after optimize   : {speed=-max, angle=0°}
  Without a fix, update_mechanism2d() takes abs(speed) so both forward and backward
  show the same arm direction. The fix adds 180° to cmd_angle when speed < 0 so the
  arm points in the actual direction of wheel travel.
"""

# Native imports
import unittest
from unittest.mock import patch

# Third-party imports
import rev
import wpilib
import wpilib.simulation
from wpimath.geometry import Rotation2d
from wpimath.kinematics import SwerveModuleState
from wpimath.system.plant import DCMotor

# Internal imports
from config import OperatorRobotConfig
from constants import SwerveDriveConsts, SwerveModuleName
from subsystem.drivetrain.swerve_module import (
    SwerveModuleMk4iSparkMaxNeoCanCoder,
    _MECH_ARM_MIN_LEN,
    _MECH_ARM_MAX_LEN,
)

_MAX_SPEED = SwerveDriveConsts.maxTranslationMPS

_MODULE_NAMES = list(SwerveModuleName)
_MODULE_LOCATIONS = [
    SwerveDriveConsts.moduleLocations[name] for name in SwerveModuleName
]
_CALIBRATIONS = OperatorRobotConfig.swerve_abs_encoder_calibrations
# Use test-only CAN IDs (1, 4, 7, 10) so these modules never conflict with
# the running robot (which uses IDs 50, 53, 56, 59).  This is needed because
# pyfrc's robot-lifecycle tests re-run all collected test files inside the
# pyfrc_test.py robot subprocess; using distinct IDs keeps hardware isolated.
_TEST_CHANNELS = (1, 4, 7, 10)


class TestSwerveMechanism(unittest.TestCase):
    """
    Test suite for swerve module Mechanism2d visualization.
    Generated by Claude.

    Uses setUpClass/tearDownClass so that each SparkMax CAN ID is only ever
    instantiated once (REV enforces one instance per ID).
    """

    @classmethod
    def setUpClass(cls):
        """Create all 4 swerve modules with sim objects and Mechanism2d once."""
        wpilib.simulation.pauseTiming()

        cls.modules = []
        cls.drive_sims = []
        cls.steer_sims = []

        for i in range(4):
            module = SwerveModuleMk4iSparkMaxNeoCanCoder(
                _MODULE_NAMES[i],
                _MODULE_LOCATIONS[i],
                _TEST_CHANNELS[i],
                invert_drive=True,
                invert_steer=True,
                encoder_calibration=_CALIBRATIONS[i],
            )
            cls.modules.append(module)
            cls.drive_sims.append(rev.SparkSim(module.drive_motor, DCMotor.NEO()))
            cls.steer_sims.append(rev.SparkSim(module.steer_motor, DCMotor.NEO()))

        # Create a shared Mechanism2d canvas and configure every module once.
        cls.mech2d = wpilib.Mechanism2d(300, 300)
        for i, module in enumerate(cls.modules):
            root = cls.mech2d.getRoot(module.name, 50 + i * 50, 150)
            module.configure_mechanism2d(
                root,
                _MAX_SPEED,
                f"test/{module.name}/threshold",
            )

    def setUp(self):
        """Reset all modules to steer=0° (forward) before each test."""
        wpilib.simulation.restartTiming()
        wpilib.simulation.pauseTiming()

        for i, module in enumerate(self.modules):
            # Set CANcoder raw = -calibration so absolute position reads 0.0 (forward).
            # current_raw_absolute_steer_position() uses is-not-None so 0.0 is
            # accepted directly (0.0 * 360 = 0°), same as the relative encoder below.
            module.absolute_encoder.sim_state.set_raw_position(-_CALIBRATIONS[i])
            module.absolute_encoder.sim_state.set_supply_voltage(12.0)

            # Force relative encoders to the forward position (0°) and 0 m/s.
            steer_enc = self.steer_sims[i].getRelativeEncoderSim()
            steer_enc.setPosition(0.0)
            steer_enc.setVelocity(0.0)

            drive_enc = self.drive_sims[i].getRelativeEncoderSim()
            drive_enc.setPosition(0.0)
            drive_enc.setVelocity(0.0)

            # Clear any previous commanded state.
            module._last_commanded_state = SwerveModuleState(0, Rotation2d())

        # Advance one cycle so all sim state changes propagate.
        wpilib.simulation.stepTiming(0.02)

    # -----------------------------------------------------------------------
    # set_state() behaviour tests
    # These verify that optimize() works as expected from the forward position.
    # -----------------------------------------------------------------------

    def test_set_state_forward_stores_positive_speed(self):
        """set_state with angle=0° at max speed must store positive speed (no flip).

        Uses mock to guarantee steer reads exactly 0° regardless of Phoenix6 sim state.
        """
        for i in range(4):
            with self.subTest(module=_MODULE_NAMES[i]):
                with patch.object(
                    self.modules[i],
                    'current_raw_absolute_steer_position',
                    return_value=0.0
                ):
                    self.modules[i].set_state(
                        SwerveModuleState(_MAX_SPEED, Rotation2d.fromDegrees(0))
                    )
                speed = self.modules[i]._last_commanded_state.speed
                self.assertGreater(
                    speed, 0,
                    msg=f"{_MODULE_NAMES[i]}: forward should give +speed, got {speed}"
                )

    def test_set_state_forward_stores_zero_angle(self):
        """set_state with angle=0° must store 0° in the commanded state.

        Uses mock to guarantee steer reads exactly 0° regardless of Phoenix6 sim state.
        """
        for i in range(4):
            with self.subTest(module=_MODULE_NAMES[i]):
                with patch.object(
                    self.modules[i],
                    'current_raw_absolute_steer_position',
                    return_value=0.0
                ):
                    self.modules[i].set_state(
                        SwerveModuleState(_MAX_SPEED, Rotation2d.fromDegrees(0))
                    )
                wrapped = self.modules[i]._last_commanded_state.angle.degrees() % 360
                distance_from_zero = min(wrapped, 360.0 - wrapped)
                self.assertLess(
                    distance_from_zero, 0.5,
                    msg=f"{_MODULE_NAMES[i]}: forward should give ≈0° angle, got {wrapped}°"
                )

    def test_set_state_backward_optimize_flips_to_negative_speed(self):
        """set_state with angle=180° from steer=0° must flip to negative speed (optimize).

        Uses mock to guarantee steer reads exactly 0° regardless of Phoenix6 sim state.
        """
        for i in range(4):
            with self.subTest(module=_MODULE_NAMES[i]):
                with patch.object(
                    self.modules[i],
                    'current_raw_absolute_steer_position',
                    return_value=0.0
                ):
                    self.modules[i].set_state(
                        SwerveModuleState(_MAX_SPEED, Rotation2d.fromDegrees(180))
                    )
                speed = self.modules[i]._last_commanded_state.speed
                self.assertLess(
                    speed, 0,
                    msg=(
                        f"{_MODULE_NAMES[i]}: backward from 0° should optimize to "
                        f"negative speed, got {speed}"
                    )
                )

    def test_set_state_backward_optimize_flips_angle_to_zero(self):
        """set_state with angle=180° from steer=0° must flip angle to 0° (optimize).

        Uses mock to guarantee steer reads exactly 0° regardless of Phoenix6 sim state.
        Uses a wrap-aware comparison because Rotation2d arithmetic can produce
        values like -1e-14°, which after float modulo gives 360.0 instead of 0.0.
        """
        for i in range(4):
            with self.subTest(module=_MODULE_NAMES[i]):
                with patch.object(
                    self.modules[i],
                    'current_raw_absolute_steer_position',
                    return_value=0.0
                ):
                    self.modules[i].set_state(
                        SwerveModuleState(_MAX_SPEED, Rotation2d.fromDegrees(180))
                    )
                raw_angle = self.modules[i]._last_commanded_state.angle.degrees()
                # Normalize to [0, 360) then take the shorter arc to 0°.
                # Handles the float precision case where 360° - epsilon rounds to 360.0.
                wrapped = raw_angle % 360
                distance_from_zero = min(wrapped, 360.0 - wrapped)
                self.assertLess(
                    distance_from_zero, 0.5,
                    msg=(
                        f"{_MODULE_NAMES[i]}: backward from 0° should optimize "
                        f"angle to ≈0°, got {raw_angle:.6f}° "
                        f"(wrapped={wrapped:.6f}°)"
                    )
                )

    # -----------------------------------------------------------------------
    # Mechanism2d arm tests
    # _last_commanded_state is set directly so these tests are independent of
    # encoder sim accuracy.
    # -----------------------------------------------------------------------

    def test_mechanism_forward_arm_angle(self):
        """
        Forward motion: commanded arm must point in the forward direction.

        Canvas angle = robot_angle(0°) + 90° + module_offset.
        """
        for i, module in enumerate(self.modules):
            with self.subTest(module=_MODULE_NAMES[i]):
                module._last_commanded_state = SwerveModuleState(
                    _MAX_SPEED, Rotation2d.fromDegrees(0)
                )
                module.update_mechanism2d()

                expected = 90  # robot 0° + 90° canvas offset = pointing forward (up)
                actual = module._mech_commanded_arm.getAngle() % 360
                self.assertAlmostEqual(
                    actual, expected, places=1,
                    msg=(
                        f"{_MODULE_NAMES[i]}: forward arm angle wrong. "
                        f"Expected {expected}°, got {actual}°"
                    )
                )

    def test_mechanism_backward_arm_angle(self):
        """
        Backward motion: commanded arm must point in the backward direction (180° robot-frame).

        After optimize(), backward motion is stored as {speed=-max, angle=0°}.
        update_mechanism2d() must detect the negative speed and add 180° to the
        display angle so the arm shows the actual direction of wheel travel.

        Canvas angle = (0° + 180°_flip + 90° + module_offset).

        This test FAILS if update_mechanism2d() does not flip the angle for
        negative speed, because the arm would point the same way as forward.
        """
        for i, module in enumerate(self.modules):
            with self.subTest(module=_MODULE_NAMES[i]):
                # Simulate the post-optimize state for backward motion from steer=0°.
                module._last_commanded_state = SwerveModuleState(
                    -_MAX_SPEED, Rotation2d.fromDegrees(0)
                )
                module.update_mechanism2d()

                expected = 270  # (0° + 180° flip + 90° canvas offset) = pointing backward (down)
                actual = module._mech_commanded_arm.getAngle() % 360
                self.assertAlmostEqual(
                    actual, expected, places=1,
                    msg=(
                        f"{_MODULE_NAMES[i]}: backward arm angle wrong. "
                        f"Expected {expected}° (backward), got {actual}°. "
                        f"update_mechanism2d() must flip angle 180° for negative speed."
                    )
                )

    def test_mechanism_forward_arm_max_length(self):
        """Forward at max speed: commanded arm must have maximum arm length."""
        for i, module in enumerate(self.modules):
            with self.subTest(module=_MODULE_NAMES[i]):
                module._last_commanded_state = SwerveModuleState(
                    _MAX_SPEED, Rotation2d.fromDegrees(0)
                )
                module.update_mechanism2d()

                self.assertAlmostEqual(
                    module._mech_commanded_arm.getLength(), _MECH_ARM_MAX_LEN, places=1,
                    msg=(
                        f"{_MODULE_NAMES[i]}: expected max arm length "
                        f"{_MECH_ARM_MAX_LEN}, got {module._mech_commanded_arm.getLength()}"
                    )
                )

    def test_mechanism_backward_arm_max_length(self):
        """Backward at max speed: commanded arm must have maximum arm length (|speed| = max)."""
        for i, module in enumerate(self.modules):
            with self.subTest(module=_MODULE_NAMES[i]):
                module._last_commanded_state = SwerveModuleState(
                    -_MAX_SPEED, Rotation2d.fromDegrees(0)
                )
                module.update_mechanism2d()

                self.assertAlmostEqual(
                    module._mech_commanded_arm.getLength(), _MECH_ARM_MAX_LEN, places=1,
                    msg=(
                        f"{_MODULE_NAMES[i]}: expected max arm length "
                        f"{_MECH_ARM_MAX_LEN}, got {module._mech_commanded_arm.getLength()}"
                    )
                )

    def test_mechanism_zero_speed_arm_min_length(self):
        """At zero speed: commanded arm must fall back to minimum arm length."""
        for i, module in enumerate(self.modules):
            with self.subTest(module=_MODULE_NAMES[i]):
                module._last_commanded_state = SwerveModuleState(0, Rotation2d())
                module.update_mechanism2d()

                self.assertAlmostEqual(
                    module._mech_commanded_arm.getLength(), _MECH_ARM_MIN_LEN, places=1,
                    msg=(
                        f"{_MODULE_NAMES[i]}: expected min arm length "
                        f"{_MECH_ARM_MIN_LEN}, got {module._mech_commanded_arm.getLength()}"
                    )
                )


if __name__ == "__main__":
    unittest.main()
