"""
Unit tests for the IntakeSubsystem.
# Generated by Claude

Tests validate:
- Roller request methods set correct power multipliers
- requestRollerOn/Off are non-blocking (no while loops)
- Pivot power is set correctly for deploy/stow
- motorChecks drives motors using power * speed
- Periodic runs without error
"""

import rev
import wpilib.simulation
from wpimath.system.plant import DCMotor

from subsystem.intakeactions import IntakeSubsystem


class TestIntakeRoller:
    """Tests for roller request/query methods."""

    @classmethod
    def setup_class(cls):
        wpilib.simulation.pauseTiming()
        cls.intake = IntakeSubsystem()
        cls.roller_sim = rev.SparkSim(cls.intake.rollerMotor, DCMotor.neoVortex())
        cls.roller_sim.setBusVoltage(12.0)
        cls.pivot_sim = rev.SparkSim(cls.intake.pivotMotor, DCMotor.neoVortex())
        cls.pivot_sim.setBusVoltage(12.0)

    def setup_method(self):
        self.intake.rollerSetpoint = 0.0
        self.intake.pivotSetpoint = 0.0
        self.intake.rollerStoppedOnce = False
        self.intake.jamDetected = False
        self.intake.jamTimingActive = False

    def test_request_roller_on_sets_setpoint(self):
        self.intake.requestRollerOn()
        assert self.intake.rollerSetpoint == self.intake.rollerBaseSpeed

    def test_request_roller_off_sets_setpoint(self):
        self.intake.rollerSetpoint = self.intake.rollerBaseSpeed
        self.intake.requestRollerOff()
        assert self.intake.rollerSetpoint == 0

    def test_request_roller_on_clears_stopped_once(self):
        self.intake.rollerStoppedOnce = True
        self.intake.requestRollerOn()
        assert self.intake.rollerStoppedOnce is False

    def test_request_roller_on_is_nonblocking(self):
        """requestRollerOn must return immediately, not block on velocity."""
        self.intake.requestRollerOn()
        # If we got here, it didn't block
        assert self.intake.rollerSetpoint == self.intake.rollerBaseSpeed

    def test_request_roller_off_is_nonblocking(self):
        """requestRollerOff must return immediately, not block on velocity."""
        self.intake.rollerSetpoint = 1
        self.intake.requestRollerOff()
        assert self.intake.rollerSetpoint == 0

    def test_roller_setpoint_forward(self):
        self.intake.requestRollerOn()
        assert self.intake.rollerSetpoint == self.intake.rollerBaseSpeed

    def test_roller_setpoint_off(self):
        self.intake.requestRollerOff()
        assert self.intake.rollerSetpoint == 0


class TestIntakePivot:
    """Tests for pivot deploy/stow power setting.

    Reuses the same IntakeSubsystem instance since SparkFlex
    enforces one instance per CAN ID.
    """

    @classmethod
    def setup_class(cls):
        wpilib.simulation.pauseTiming()
        # Reuse the same subsystem — can't create a second SparkFlex on same CAN IDs
        cls.intake = TestIntakeRoller.intake
        cls.pivot_sim = TestIntakeRoller.pivot_sim
        cls.roller_sim = TestIntakeRoller.roller_sim

    def setup_method(self):
        self.intake.pivotSetpoint = 0.0
        self.intake.pivotSpeed = 0.3
        self.intake.rollerSetpoint = 0.0
        self.intake.pivotRamping = False
        self.intake.rampPower = 0.0
        self.intake.pivotRampComplete = False
        self.pivot_sim.setPosition(0.0)

    def test_deploy_sets_positive_setpoint(self):
        """With encoder at 0 (below deployed limit), deployIntake should set positive setpoint."""
        self.intake.pivotMotorEncoder.setPosition(0.0)
        self.intake.deployIntake()
        assert self.intake.pivotSetpoint == self.intake.pivotBaseSpeed

    def test_stow_sets_negative_setpoint(self):
        """With encoder past stowed, stowIntake should set negative setpoint."""
        self.intake.pivotMotorEncoder.setPosition(50.0)
        self.intake.pivotSetpoint = 0.0
        self.intake.stowIntake()
        assert self.intake.pivotSetpoint == -self.intake.pivotBaseSpeed

    def test_deploy_stops_at_limit(self):
        """When encoder is past deployed limit, deployIntake should zero setpoint."""
        self.intake.pivotMotorEncoder.setPosition(self.intake.pivotDeployed + 1)
        self.intake.pivotSetpoint = self.intake.pivotBaseSpeed
        self.intake.deployIntake()
        assert self.intake.pivotSetpoint == 0

    def test_stow_stops_at_limit(self):
        """When encoder is past stowed limit, stowIntake should zero setpoint."""
        self.intake.pivotMotorEncoder.setPosition(self.intake.pivotStowed - 1)
        self.intake.pivotSetpoint = -self.intake.pivotBaseSpeed
        self.intake.stowIntake()
        assert self.intake.pivotSetpoint == 0

    def test_pivot_slowdown_deploy(self):
        self.intake.pivotSetpoint = self.intake.pivotBaseSpeed
        # Position past 75% of travel
        self.intake.pivotMotorEncoder.setPosition(self.intake.pivotDeployed * 0.8)
        self.intake.pivotSlowdown()
        assert self.intake.pivotSetpoint == self.intake.pivotBaseSpeed / 2

    def test_pivot_slowdown_stow(self):
        self.intake.pivotSetpoint = -self.intake.pivotBaseSpeed
        self.intake.pivotDeployed = 155
        self.intake.pivotStowed = 0
        # Position past 75% of stow travel (near 0)
        self.intake.pivotMotorEncoder.setPosition(self.intake.pivotDeployed * 0.2)
        self.intake.pivotSlowdown()
        assert self.intake.pivotSetpoint == -self.intake.pivotBaseSpeed / 2

    def test_periodic_runs_without_error(self):
        """Smoke test: periodic() should not raise."""
        self.intake.periodic()
