"""
Unit tests for IntakePosition and IntakeRoller subsystems.
# Generated by Claude

Tests validate:
- IntakeRoller: setPower/stop/getPower via SimpleMotorSubsystem base
- IntakePosition: deploy/stow convenience methods, position setting,
  calibration blocking, periodic runs without error
"""

import rev
import wpilib.simulation
from wpimath.system.plant import DCMotor

from subsystem.mechanisms.intake.intake_position import IntakePosition
from subsystem.mechanisms.intake.intake_roller import IntakeRoller
from constants.swerve_constants import IntakeRollerConstants, IntakePivotConstants


class TestIntakeRoller:
    """Tests for the IntakeRoller subsystem (SimpleMotorSubsystem)."""

    @classmethod
    def setup_class(cls):
        wpilib.simulation.pauseTiming()
        cls.roller = IntakeRoller()
        cls.roller_sim = rev.SparkSim(cls.roller.motor, DCMotor.neoVortex())
        cls.roller_sim.setBusVoltage(12.0)

    def setup_method(self):
        self.roller.stop()

    def test_set_power(self):
        self.roller.setPower(0.6)
        assert self.roller.getPower() == 0.6

    def test_stop(self):
        self.roller.setPower(0.6)
        self.roller.stop()
        assert self.roller.getPower() == 0.0

    def test_default_power_from_constants(self):
        self.roller.setPower(IntakeRollerConstants.defaultPower)
        assert self.roller.getPower() == 0.6

    def test_periodic_runs_without_error(self):
        self.roller.setPower(0.5)
        self.roller.periodic()


class TestIntakePosition:
    """Tests for the IntakePosition subsystem."""

    @classmethod
    def setup_class(cls):
        wpilib.simulation.pauseTiming()
        cls.intake = IntakePosition()
        cls.pivot_sim = rev.SparkSim(cls.intake.motor, DCMotor.neoVortex())
        cls.pivot_sim.setBusVoltage(12.0)

    def setup_method(self):
        self.intake.disable()
        self.pivot_sim.setPosition(0.0)

    def test_deploy_sets_target(self):
        self.intake.deployIntake()
        assert self.intake._target_position == IntakePivotConstants.deployedPosition

    def test_stow_sets_target(self):
        self.intake.stowIntake()
        assert self.intake._target_position == IntakePivotConstants.stowedPosition

    def test_set_position_clamps_to_limits(self):
        self.intake.setPosition(999.0)
        assert self.intake._target_position <= IntakePivotConstants.maxSoftLimit

    def test_set_position_clamps_negative(self):
        self.intake.setPosition(-999.0)
        assert self.intake._target_position >= IntakePivotConstants.minSoftLimit

    def test_is_stowed_at_zero(self):
        self.intake.encoder.setPosition(0.0)
        assert self.intake.isIntakeStowed()

    def test_is_deployed_at_limit(self):
        self.intake.encoder.setPosition(IntakePivotConstants.deployedPosition)
        assert self.intake.isIntakeDeployed()

    def test_disable_clears_target(self):
        self.intake.deployIntake()
        self.intake.disable()
        assert self.intake._target_position is None

    def test_periodic_runs_without_error(self):
        self.intake.periodic()

    def test_periodic_with_target(self):
        self.intake.setPosition(50.0)
        self.intake.periodic()
