"""Test whether a command instance can be added multiple times to a SequentialCommandGroup.
# Generated by Claude

Verifies:
1. Same instance added twice via addCommands -> raises
2. Two different instances added via addCommands -> works fine and both execute
"""

import hal
import commands2


class CounterCommand(commands2.Command):
    """Simple command that runs once and increments a shared counter."""

    def __init__(self, counter: list):
        super().__init__()
        self.counter = counter
        self.done = False

    def initialize(self):
        self.counter.append(1)
        self.done = True

    def isFinished(self) -> bool:
        return self.done

    def runsWhenDisabled(self):
        return True


def setup_module():
    hal.initialize(500, 0)


def teardown_function():
    commands2.CommandScheduler.getInstance().cancelAll()
    commands2.CommandScheduler.resetInstance()


class TestSequentialReuse:
    def test_same_instance_twice_raises(self):
        """Adding the same command instance twice via addCommands should raise."""
        counter = []
        cmd = CounterCommand(counter)
        group = commands2.SequentialCommandGroup()
        group.addCommands(cmd)
        raised = False
        try:
            group.addCommands(cmd)
        except Exception:
            raised = True
        assert raised, "Expected an exception when reusing the same command instance"

    def test_different_instances_works(self):
        """Two separate instances added via addCommands should compose fine."""
        counter = []
        group = commands2.SequentialCommandGroup()
        group.addCommands(CounterCommand(counter))
        group.addCommands(CounterCommand(counter))

        scheduler = commands2.CommandScheduler.getInstance()
        scheduler.schedule(group)
        assert scheduler.isScheduled(group), "Group should be scheduled"

        for _ in range(10):
            scheduler.run()
            if not scheduler.isScheduled(group):
                break

        assert len(counter) == 2, f"Expected counter=2, got {len(counter)}"
