"""Unit tests for NFC NDEF encoding/decoding and BatteryData model.
# Generated by Claude

Tests NDEF record encoding, TLV wrapping, roundtrip encode/decode,
battery data serialization, and edge cases.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utils.nfc.nfc_writer import (
    encode_ndef_uri_record,
    encode_ndef_text_record,
    wrap_ndef_message,
    build_battery_ndef,
)
from utils.nfc.nfc_reader import (
    parse_ndef_text_records,
    parse_ndef_uri_records,
    NfcTagData,
)
from host.nfc_tool.battery_data import BatteryData


# --- NDEF Encoding ---

class TestNdefUriRecord:
    def test_http_www_prefix_compression(self):
        rec = encode_ndef_uri_record('http://www.raptacon.org',
                                     first=True, last=True)
        # Should use prefix code 0x01 for 'http://www.'
        # Payload: [0x01] + 'raptacon.org'
        assert b'U' in rec
        assert b'raptacon.org' in rec
        # Prefix 0x01 should be in payload (after type byte 'U')
        u_idx = rec.index(ord('U'))
        assert rec[u_idx + 1] == 0x01  # prefix code

    def test_https_prefix(self):
        rec = encode_ndef_uri_record('https://example.com',
                                     first=True, last=True)
        u_idx = rec.index(ord('U'))
        assert rec[u_idx + 1] == 0x04  # 'https://' prefix code

    def test_no_prefix_match(self):
        rec = encode_ndef_uri_record('ftp://files.example.com',
                                     first=True, last=True)
        u_idx = rec.index(ord('U'))
        assert rec[u_idx + 1] == 0x00  # no prefix

    def test_mb_me_flags(self):
        rec_first = encode_ndef_uri_record('http://x.com', first=True,
                                           last=False)
        rec_last = encode_ndef_uri_record('http://x.com', first=False,
                                          last=True)
        assert rec_first[0] & 0x80  # MB set
        assert not (rec_first[0] & 0x40)  # ME not set
        assert not (rec_last[0] & 0x80)  # MB not set
        assert rec_last[0] & 0x40  # ME set


class TestNdefTextRecord:
    def test_basic_text(self):
        rec = encode_ndef_text_record('hello', first=True, last=True)
        assert b'T' in rec
        assert b'en' in rec
        assert b'hello' in rec

    def test_lang_code_length(self):
        rec = encode_ndef_text_record('test', lang='en', first=True,
                                      last=True)
        # Status byte should have lang length = 2
        t_idx = rec.index(ord('T'))
        status = rec[t_idx + 1]
        assert (status & 0x3F) == 2  # 'en' is 2 bytes

    def test_utf8_encoding(self):
        rec = encode_ndef_text_record('test', first=True, last=True)
        t_idx = rec.index(ord('T'))
        status = rec[t_idx + 1]
        assert (status & 0x80) == 0  # bit 7 = 0 means UTF-8


class TestNdefTlvWrapping:
    def test_short_message(self):
        rec = encode_ndef_uri_record('http://www.raptacon.org',
                                     first=True, last=True)
        tlv = wrap_ndef_message([rec])
        assert tlv[0] == 0x03  # NDEF Message TLV
        assert tlv[-1] == 0xFE  # Terminator
        msg_len = tlv[1]
        assert msg_len == len(rec)

    def test_terminator_present(self):
        rec = encode_ndef_text_record('x', first=True, last=True)
        tlv = wrap_ndef_message([rec])
        assert tlv[-1] == 0xFE


# --- NDEF Roundtrip ---

class TestNdefRoundtrip:
    def test_uri_roundtrip(self):
        uri = 'http://www.raptacon.org'
        rec = encode_ndef_uri_record(uri, first=True, last=True)
        tlv = wrap_ndef_message([rec])
        parsed = parse_ndef_uri_records(tlv)
        assert len(parsed) == 1
        assert parsed[0] == uri

    def test_text_roundtrip(self):
        text = "bat:\nsn=BAT-001\nyear=2025"
        rec = encode_ndef_text_record(text, first=True, last=True)
        tlv = wrap_ndef_message([rec])
        parsed = parse_ndef_text_records(tlv)
        assert len(parsed) == 1
        assert parsed[0] == text

    def test_two_record_roundtrip(self):
        uri = 'http://www.raptacon.org'
        text = "bat:\nsn=BAT-042\nyear=2026\nnote=Test battery"

        uri_rec = encode_ndef_uri_record(uri, first=True, last=False)
        text_rec = encode_ndef_text_record(text, first=False, last=True)
        tlv = wrap_ndef_message([uri_rec, text_rec])

        uris = parse_ndef_uri_records(tlv)
        texts = parse_ndef_text_records(tlv)
        assert uris == [uri]
        assert texts == [text]

    def test_build_battery_ndef_roundtrip(self):
        data = build_battery_ndef(sn='BAT-007', year='2025',
                                  note='Competition')
        tag = NfcTagData(uid=b'\x04\x01\x02\x03\x04\x05\x06',
                         user_data=data)
        assert tag.get_uri() == 'http://www.raptacon.org'
        text = tag.get_text()
        assert 'bat:' in text
        assert 'sn=BAT-007' in text
        assert 'year=2025' in text
        assert 'note=Competition' in text


# --- BatteryData ---

class TestBatteryData:
    def test_from_text_with_bat_prefix(self):
        text = "bat:\nsn=BAT-001\nyear=2025\nnote=New"
        bat = BatteryData.from_text(text)
        assert bat.sn == 'BAT-001'
        assert bat.year == '2025'
        assert bat.note == 'New'

    def test_from_text_ignores_unknown_keys(self):
        text = "bat:\nsn=X\nyear=2025\nfoo=bar"
        bat = BatteryData.from_text(text)
        assert bat.sn == 'X'
        assert bat.year == '2025'
        assert bat.note == ''

    def test_to_text_roundtrip(self):
        bat = BatteryData(sn='BAT-042', year='2026', note='Test')
        text = bat.to_text()
        bat2 = BatteryData.from_text(text)
        assert bat2.sn == bat.sn
        assert bat2.year == bat.year
        assert bat2.note == bat.note

    def test_to_text_omits_empty_note(self):
        bat = BatteryData(sn='BAT-001', year='2025')
        text = bat.to_text()
        assert 'note=' not in text

    def test_is_valid(self):
        assert BatteryData(sn='BAT-001').is_valid()
        assert not BatteryData(sn='').is_valid()
        assert not BatteryData(sn='  ').is_valid()

    def test_from_text_without_bat_prefix(self):
        text = "sn=BAT-001\nyear=2025"
        bat = BatteryData.from_text(text)
        assert bat.sn == 'BAT-001'


# --- NfcTagData ---

class TestNfcTagData:
    def test_uid_hex(self):
        tag = NfcTagData(uid=b'\x04\xAB\xCD\xEF\x01\x02\x03')
        assert tag.uid_hex == '04ABCDEF010203'

    def test_empty_user_data(self):
        tag = NfcTagData(uid=b'\x04\x01\x02\x03')
        assert tag.get_text() == ''
        assert tag.get_uri() == ''
        assert tag.get_text_records() == []
        assert tag.get_uri_records() == []

    def test_get_uri_returns_first(self):
        # Build two URI records
        r1 = encode_ndef_uri_record('http://a.com', first=True,
                                    last=False)
        r2 = encode_ndef_uri_record('http://b.com', first=False,
                                    last=True)
        tlv = wrap_ndef_message([r1, r2])
        tag = NfcTagData(uid=b'\x04\x01', user_data=tlv)
        assert tag.get_uri() == 'http://a.com'
        assert len(tag.get_uri_records()) == 2


# --- build_battery_ndef edge cases ---

class TestBuildBatteryNdef:
    def test_no_uri(self):
        data = build_battery_ndef(sn='BAT-001', year='2025', uri='')
        texts = parse_ndef_text_records(data)
        uris = parse_ndef_uri_records(data)
        assert len(texts) == 1
        assert len(uris) == 0
        assert 'sn=BAT-001' in texts[0]

    def test_no_note(self):
        data = build_battery_ndef(sn='BAT-001', year='2025')
        texts = parse_ndef_text_records(data)
        assert 'note=' not in texts[0]

    def test_size_validation(self):
        try:
            build_battery_ndef(sn='X' * 1000, year='2025',
                               max_bytes=50)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert 'exceeds' in str(e)
