"""
Unit tests for the PositionCalibration utility class.
Generated by Claude.

Standalone tests covering homing, calibration, margin, persistence,
telemetry, and abort behavior. Uses CAN ID 41 to avoid conflict with
turret tests (CAN ID 40).
"""

# Native imports
import unittest

# Third-party imports
import rev
import wpilib
import wpilib.simulation
from wpimath.system.plant import DCMotor

# Internal imports
import ntcore
from utils.position_calibration import (
    PositionCalibration, _calibration_classes, _VALID_CALLBACKS
)


class TestPositionCalibration(unittest.TestCase):
    """Test suite for the PositionCalibration utility class."""

    MOTOR_CAN_ID = 41
    MIN_SOFT_LIMIT = -90.0
    MAX_SOFT_LIMIT = 90.0

    @classmethod
    def setUpClass(cls):
        """Create motor and simulation objects once for all tests."""
        wpilib.simulation.pauseTiming()
        cls.motor = rev.SparkMax(
            cls.MOTOR_CAN_ID,
            rev.SparkLowLevel.MotorType.kBrushless
        )
        # Configure encoder conversion factor
        config = rev.SparkMaxConfig()
        config.encoder.positionConversionFactor(3.6)
        config.encoder.velocityConversionFactor(3.6 / 60.0)
        (
            config.softLimit
            .forwardSoftLimit(cls.MAX_SOFT_LIMIT)
            .forwardSoftLimitEnabled(True)
            .reverseSoftLimit(cls.MIN_SOFT_LIMIT)
            .reverseSoftLimitEnabled(True)
        )
        config.smartCurrentLimit(40)
        cls.motor.configure(
            config,
            rev.ResetMode.kResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        cls.encoder = cls.motor.getEncoder()
        cls.motor_sim = rev.SparkSim(cls.motor, DCMotor.NEO())
        cls.motor_sim.setBusVoltage(12.0)

    def setUp(self):
        """Reset calibration state before each test."""
        # restartTiming() makes existing NT topic handles read-only,
        # so we must unpublish them, clear the ntproperty class cache,
        # and let PositionCalibration recreate fresh entries.
        wpilib.simulation.restartTiming()
        wpilib.simulation.pauseTiming()

        # Unpublish calibration topics so fresh entries can write
        inst = ntcore.NetworkTableInstance.getDefault()
        prefix = "/TestMech/calibration"
        for key in ["hard_limit_min", "hard_limit_max", "soft_limit_margin"]:
            inst.getEntry(f"{prefix}/{key}").unpublish()
        for cb_name in _VALID_CALLBACKS:
            inst.getEntry(f"{prefix}/callbacks/{cb_name}").unpublish()

        # Clear ntproperty class cache so entries are recreated
        _calibration_classes.pop("TestMech", None)

        self.cal = PositionCalibration(
            name="TestMech",
            motor=self.motor,
            encoder=self.encoder,
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        # Restore soft limits on motor
        limit_config = rev.SparkMaxConfig()
        (
            limit_config.softLimit
            .forwardSoftLimit(self.MAX_SOFT_LIMIT)
            .forwardSoftLimitEnabled(True)
            .reverseSoftLimit(self.MIN_SOFT_LIMIT)
            .reverseSoftLimitEnabled(True)
        )
        limit_config.smartCurrentLimit(40)
        self.motor.configure(
            limit_config,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        self.motor.stopMotor()

    # ---- Initial state tests ----

    def test_initial_state_not_busy(self):
        """Test that a new calibration is not busy."""
        self.assertFalse(self.cal.is_busy)

    def test_initial_state_not_calibrated(self):
        """Test that a new calibration is not calibrated."""
        self.assertFalse(self.cal.is_calibrated)
        self.assertFalse(self.cal.is_zeroed)

    def test_initial_soft_limits(self):
        """Test that initial soft limits match defaults."""
        self.assertEqual(self.cal.min_soft_limit, self.MIN_SOFT_LIMIT)
        self.assertEqual(self.cal.max_soft_limit, self.MAX_SOFT_LIMIT)

    def test_initial_hard_limits_none(self):
        """Test that hard limits are None before calibration."""
        self.assertIsNone(self.cal.min_limit)
        self.assertIsNone(self.cal.max_limit)

    # ---- Homing tests ----

    def test_homing_init_sets_busy(self):
        """Test that homing_init sets is_busy and is_homing."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertTrue(self.cal.is_busy)
        self.assertTrue(self.cal.is_homing)
        self.assertFalse(self.cal.is_calibrating)

    def test_homing_forward_drives_positive(self):
        """Test that forward homing drives motor with positive duty cycle."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.3,
            max_homing_time=5.0, homing_forward=True
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)
        self.cal._homing_periodic()
        self.assertAlmostEqual(self.motor.get(), 0.3, places=1)

    def test_homing_reverse_drives_negative(self):
        """Test that reverse homing drives motor with negative duty cycle."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.3,
            max_homing_time=5.0, homing_forward=False
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(-50.0)
        self.cal._homing_periodic()
        self.assertAlmostEqual(self.motor.get(), -0.3, places=1)

    def test_homing_stall_detection(self):
        """Test stall detection completes homing after 100ms."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        result = self.cal._homing_periodic()
        self.assertFalse(result)

        wpilib.simulation.stepTiming(0.15)

        result = self.cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(self.cal.is_homing)

    def test_homing_timeout(self):
        """Test that homing times out correctly."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=0.5,
            homing_forward=True,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)

        wpilib.simulation.stepTiming(0.6)

        result = self.cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(self.cal.is_homing)

    def test_homing_restores_settings(self):
        """Test that homing end restores motor settings."""
        original_current = self.motor.configAccessor.getSmartCurrentLimit()
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertAlmostEqual(
            self.motor.configAccessor.getSmartCurrentLimit(), 10.0, places=0)

        self.cal._homing_end(abort=False)

        self.assertAlmostEqual(
            self.motor.configAccessor.getSmartCurrentLimit(),
            original_current, places=0)
        self.assertTrue(
            self.motor.configAccessor.softLimit.getForwardSoftLimitEnabled())

    def test_homing_sets_encoder_forward(self):
        """Test encoder reset to home_position on forward homing complete."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)
        self.cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._homing_periodic()

        self.assertAlmostEqual(
            self.encoder.getPosition(), 0.0, places=1)

    def test_homing_sets_encoder_reverse(self):
        """Test encoder reset to home_position on reverse homing complete."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)
        self.cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._homing_periodic()

        self.assertAlmostEqual(
            self.encoder.getPosition(), 0.0, places=1)

    # ---- Calibration tests ----

    def test_calibration_init_sets_state(self):
        """Test that calibration_init sets flags and starts phase 1."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        self.assertTrue(self.cal.is_calibrating)
        self.assertTrue(self.cal.is_homing)
        self.assertTrue(self.cal.is_busy)
        self.assertEqual(self.cal._calibration_phase, 1)

    def test_calibration_full_two_phase(self):
        """Test complete two-phase calibration discovers full range."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # Phase 1: stall reverse
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal._calibration_phase, 2)

        # Phase 2: set position and stall forward
        encoder_sim.setPosition(180.0)
        encoder_sim.setVelocity(0.0)
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertFalse(self.cal.is_calibrating)
        self.assertTrue(self.cal.is_calibrated)
        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal.max_limit, 180.0)

    def test_calibration_known_range(self):
        """Test single-direction calibration with known range."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0,
            known_range=200.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # Phase 1 only
        self.cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        self.cal._calibration_periodic()

        self.assertTrue(self.cal.is_calibrated)
        self.assertEqual(self.cal.min_limit, 0.0)
        self.assertEqual(self.cal.max_limit, 200.0)

    def test_calibration_abort(self):
        """Test that abort clears calibration state."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        self.cal.abort()

        self.assertFalse(self.cal.is_busy)
        self.assertFalse(self.cal.is_calibrated)
        # Motor settings should be restored
        ca = self.motor.configAccessor
        self.assertTrue(ca.softLimit.getForwardSoftLimitEnabled())
        self.assertTrue(ca.softLimit.getReverseSoftLimitEnabled())

    def test_calibration_abort_during_homing(self):
        """Test that abort works when only homing is active."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.cal.abort()
        self.assertFalse(self.cal.is_busy)

    # ---- Soft limit margin tests ----

    def test_soft_limit_margin_default(self):
        """Test default soft limit margin is 5%."""
        self.assertAlmostEqual(self.cal.soft_limit_margin, 0.05)

    def test_set_soft_limit_margin_when_calibrated(self):
        """Test set_soft_limit_margin applies margins correctly."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 0.0
        self.cal._hard_limit_max = 200.0
        self.cal.set_soft_limit_margin(0.10)

        self.assertAlmostEqual(self.cal.min_soft_limit, 20.0, places=1)
        self.assertAlmostEqual(self.cal.max_soft_limit, 180.0, places=1)
        self.assertAlmostEqual(self.cal.soft_limit_margin, 0.10)

    def test_set_soft_limit_margin_applies_to_motor(self):
        """Test that set_soft_limit_margin updates motor controller."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 0.0
        self.cal._hard_limit_max = 100.0
        self.cal.set_soft_limit_margin(0.05)

        ca = self.motor.configAccessor
        self.assertTrue(ca.softLimit.getForwardSoftLimitEnabled())
        self.assertTrue(ca.softLimit.getReverseSoftLimitEnabled())
        self.assertAlmostEqual(
            ca.softLimit.getForwardSoftLimit(), 95.0, places=1)
        self.assertAlmostEqual(
            ca.softLimit.getReverseSoftLimit(), 5.0, places=1)

    def test_set_soft_limit_margin_noop_uncalibrated(self):
        """Test set_soft_limit_margin does nothing when uncalibrated."""
        original_min = self.cal.min_soft_limit
        original_max = self.cal.max_soft_limit
        self.cal.set_soft_limit_margin(0.10)
        self.assertEqual(self.cal.min_soft_limit, original_min)
        self.assertEqual(self.cal.max_soft_limit, original_max)

    # ---- Persistence tests ----

    def test_save_and_load_from_nt(self):
        """Test that calibration data persists via NT Preferences."""
        # Calibrate
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 5.0
        self.cal._hard_limit_max = 195.0
        self.cal._soft_limit_margin = 0.08
        self.cal._save_to_nt()

        # Create a new instance - should load persisted data
        cal2 = PositionCalibration(
            name="TestMech",
            motor=self.motor,
            encoder=self.encoder,
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        self.assertTrue(cal2.is_calibrated)
        self.assertEqual(cal2.min_limit, 5.0)
        self.assertEqual(cal2.max_limit, 195.0)
        self.assertAlmostEqual(cal2.soft_limit_margin, 0.08)

    def test_no_load_when_no_persisted_data(self):
        """Test that missing NT data doesn't mark as calibrated."""
        cal = PositionCalibration(
            name="NoData",
            motor=self.motor,
            encoder=self.encoder,
            fallback_min=-45.0,
            fallback_max=45.0,
        )
        self.assertFalse(cal.is_calibrated)
        self.assertIsNone(cal.min_limit)
        self.assertIsNone(cal.max_limit)

    # ---- Telemetry tests ----

    def test_update_telemetry_publishes_keys(self):
        """Test that update_telemetry publishes expected keys."""
        prefix = "TestMech/"
        self.cal.update_telemetry(prefix)
        sd = wpilib.SmartDashboard
        self.assertTrue(sd.containsKey(prefix + "isCalibrated"))
        self.assertTrue(sd.containsKey(prefix + "isCalibrating"))
        self.assertTrue(sd.containsKey(prefix + "isHoming"))
        self.assertTrue(sd.containsKey(prefix + "hardLimitMin"))
        self.assertTrue(sd.containsKey(prefix + "hardLimitMax"))
        self.assertTrue(sd.containsKey(prefix + "positionOffset"))
        self.assertTrue(sd.containsKey(prefix + "softLimitMargin"))

    def test_telemetry_reflects_state(self):
        """Test that telemetry values match internal state."""
        self.cal._is_calibrated = True
        self.cal._hard_limit_min = 10.0
        self.cal._hard_limit_max = 170.0
        prefix = "TestMech/"
        self.cal.update_telemetry(prefix)
        sd = wpilib.SmartDashboard
        self.assertTrue(sd.getBoolean(prefix + "isCalibrated", False))
        self.assertAlmostEqual(
            sd.getNumber(prefix + "hardLimitMin", 0.0), 10.0, places=1)
        self.assertAlmostEqual(
            sd.getNumber(prefix + "hardLimitMax", 0.0), 170.0, places=1)

    # ---- Periodic routing tests ----

    def test_periodic_routes_to_calibration(self):
        """Test that periodic() calls calibration state machine."""
        self.cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(0.0)

        # periodic() should drive the calibration state machine
        self.cal.periodic()
        # Motor should be driven by homing (reverse direction)
        self.assertAlmostEqual(self.motor.get(), -0.2, places=1)

    def test_periodic_routes_to_homing(self):
        """Test that periodic() calls homing when only homing is active."""
        self.cal.homing_init(
            max_current=10.0, max_power_pct=0.25,
            max_homing_time=5.0, homing_forward=True
        )
        encoder_sim = self.motor_sim.getRelativeEncoderSim()
        encoder_sim.setVelocity(50.0)

        self.cal.periodic()
        self.assertAlmostEqual(self.motor.get(), 0.25, places=2)


class TestPositionCalibrationCallbacks(unittest.TestCase):
    """
    Test suite for the callback-based PositionCalibration interface.
    Generated by Claude.

    Pure-callback tests with no SparkMax hardware dependencies.
    """

    MIN_SOFT_LIMIT = -90.0
    MAX_SOFT_LIMIT = 90.0

    def setUp(self):
        """Set up fresh NT state and callback tracking for each test."""
        wpilib.simulation.restartTiming()
        wpilib.simulation.pauseTiming()

        # Unpublish calibration topics
        inst = ntcore.NetworkTableInstance.getDefault()
        for name in ["CbTest", "CbEmpty", "CbOverride"]:
            prefix = f"/{name}/calibration"
            for key in [
                "hard_limit_min", "hard_limit_max", "soft_limit_margin"
            ]:
                inst.getEntry(f"{prefix}/{key}").unpublish()
            for cb_name in _VALID_CALLBACKS:
                inst.getEntry(
                    f"{prefix}/callbacks/{cb_name}").unpublish()
            _calibration_classes.pop(name, None)

        # Mock state for callbacks
        self._position = 0.0
        self._velocity = 10.0
        self._motor_output = 0.0
        self._motor_stopped = False
        self._fwd_limit = False
        self._rev_limit = False
        self._current_limit = None
        self._soft_limits = None
        self._disabled_soft_limits = None
        self._saved = None
        self._restored = None
        self._limit_detected_calls = []

    def _make_callbacks(self, **overrides):
        """Build a full set of mock callbacks with optional overrides."""
        cbs = {
            'get_position': lambda: self._position,
            'get_velocity': lambda: self._velocity,
            'set_position': self._set_position,
            'set_motor_output': self._set_motor_output,
            'stop_motor': self._stop_motor,
            'get_forward_limit_switch': lambda: self._fwd_limit,
            'get_reverse_limit_switch': lambda: self._rev_limit,
            'set_current_limit': self._set_current_limit,
            'set_soft_limits': self._set_soft_limits,
            'disable_soft_limits': self._disable_soft_limits,
            'save_config': self._save_config,
            'restore_config': self._restore_config,
            'on_limit_detected': self._on_limit_detected,
        }
        cbs.update(overrides)
        return cbs

    def _set_position(self, v):
        self._position = v

    def _set_motor_output(self, p):
        self._motor_output = p
        self._motor_stopped = False

    def _stop_motor(self):
        self._motor_output = 0.0
        self._motor_stopped = True

    def _set_current_limit(self, amps):
        self._current_limit = amps

    def _set_soft_limits(self, min_l, max_l):
        self._soft_limits = (min_l, max_l)

    def _disable_soft_limits(self, fwd, rev):
        self._disabled_soft_limits = (fwd, rev)

    def _save_config(self):
        self._saved = {'marker': True}
        return self._saved

    def _restore_config(self, saved):
        self._restored = saved

    def _on_limit_detected(self, position, direction):
        self._limit_detected_calls.append((position, direction))

    # ---- Construction tests ----

    def test_callback_construction_no_motor(self):
        """Test construction with only callbacks (no motor param)."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        self.assertFalse(cal.is_busy)
        self.assertFalse(cal.is_calibrated)

    def test_missing_core_callback_raises(self):
        """Test that missing core callbacks raise ValueError at homing."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            get_velocity=lambda: 10.0,
        )
        with self.assertRaises(ValueError) as ctx:
            cal.homing_init(
                max_current=10.0, max_power_pct=0.2,
                max_homing_time=5.0, homing_forward=True
            )
        self.assertIn("set_motor_output", str(ctx.exception))

    def test_missing_detection_raises(self):
        """Test ValueError when no detection method for homing direction."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            set_motor_output=self._set_motor_output,
            stop_motor=self._stop_motor,
            set_position=self._set_position,
        )
        with self.assertRaises(ValueError) as ctx:
            cal.homing_init(
                max_current=10.0, max_power_pct=0.2,
                max_homing_time=5.0, homing_forward=True
            )
        self.assertIn("forward", str(ctx.exception))

    def test_calibration_requires_get_position(self):
        """Test that calibration raises without get_position callback."""
        cbs = self._make_callbacks()
        del cbs['get_position']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        with self.assertRaises(ValueError) as ctx:
            cal.calibration_init(
                max_current=10.0, max_power_pct=0.2,
                max_homing_time=5.0
            )
        self.assertIn("get_position", str(ctx.exception))

    def test_set_callbacks_after_init(self):
        """Test that callbacks can be set after construction."""
        cal = PositionCalibration(
            name="CbEmpty",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        cal.set_callbacks(
            set_motor_output=self._set_motor_output,
            stop_motor=self._stop_motor,
            set_position=self._set_position,
            get_velocity=lambda: self._velocity,
        )
        # Should not raise
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertTrue(cal.is_homing)

    def test_unknown_callback_raises(self):
        """Test that unknown callback keys raise ValueError."""
        with self.assertRaises(ValueError) as ctx:
            PositionCalibration(
                name="CbTest",
                fallback_min=self.MIN_SOFT_LIMIT,
                fallback_max=self.MAX_SOFT_LIMIT,
                not_a_real_callback=lambda: None,
            )
        self.assertIn("not_a_real_callback", str(ctx.exception))

    def test_unknown_callback_in_set_callbacks_raises(self):
        """Test that set_callbacks rejects unknown keys."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        with self.assertRaises(ValueError):
            cal.set_callbacks(bogus=lambda: None)

    # ---- Homing with different detection methods ----

    def test_homing_with_velocity_only(self):
        """Test homing via stall detection, no limit switches."""
        cbs = self._make_callbacks()
        del cbs['get_forward_limit_switch']
        del cbs['get_reverse_limit_switch']
        del cbs['on_limit_detected']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        # Set velocity to 0 for stall
        self._velocity = 0.0
        result = cal._homing_periodic()
        self.assertFalse(result)

        wpilib.simulation.stepTiming(0.15)

        result = cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(cal.is_homing)
        self.assertAlmostEqual(
            self._position, 0.0, places=1)

    def test_homing_with_limit_switch_only(self):
        """Test homing via limit switch, no velocity callback."""
        cbs = self._make_callbacks()
        del cbs['get_velocity']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        # No limit hit yet
        result = cal._homing_periodic()
        self.assertFalse(result)

        # Trigger forward limit switch
        self._fwd_limit = True
        result = cal._homing_periodic()
        self.assertTrue(result)
        self.assertFalse(cal.is_homing)
        self.assertAlmostEqual(
            self._position, 0.0, places=1)

    def test_homing_with_both_limit_switch_takes_priority(self):
        """Test that limit switch fires before stall when both present."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0
        )
        # Both velocity=0 (stall) AND limit switch on
        self._velocity = 0.0
        self._fwd_limit = True
        result = cal._homing_periodic()
        # Limit switch fires on same cycle, completes immediately
        self.assertTrue(result)
        self.assertFalse(cal.is_homing)

    # ---- on_limit_detected callback ----

    def test_on_limit_detected_fires_on_stall(self):
        """Test on_limit_detected fires with correct args on stall."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        self._velocity = 0.0
        cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._homing_periodic()

        self.assertEqual(len(self._limit_detected_calls), 1)
        pos, direction = self._limit_detected_calls[0]
        self.assertAlmostEqual(pos, 0.0, places=1)
        self.assertEqual(direction, "reverse")

    def test_on_limit_detected_not_required(self):
        """Test homing works fine when on_limit_detected is None."""
        cbs = self._make_callbacks()
        del cbs['on_limit_detected']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0
        )
        self._velocity = 0.0
        cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._homing_periodic()
        self.assertFalse(cal.is_homing)

    # ---- Calibration full sequence with callbacks ----

    def test_calibration_full_sequence_callbacks(self):
        """Test two-phase calibration with pure callbacks."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.calibration_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, min_velocity=1.0
        )
        # Phase 1: stall reverse
        self._velocity = 0.0
        cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._calibration_periodic()

        self.assertEqual(cal.min_limit, 0.0)
        self.assertEqual(cal._calibration_phase, 2)

        # Phase 2: set position and stall forward
        self._position = 180.0
        self._velocity = 0.0
        cal._calibration_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._calibration_periodic()

        self.assertFalse(cal.is_calibrating)
        self.assertTrue(cal.is_calibrated)
        self.assertEqual(cal.min_limit, 0.0)
        self.assertEqual(cal.max_limit, 180.0)

    # ---- Optional callbacks skipped gracefully ----

    def test_optional_save_restore_skipped(self):
        """Test homing works without save_config/restore_config."""
        cbs = self._make_callbacks()
        del cbs['save_config']
        del cbs['restore_config']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        self._velocity = 0.0
        cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._homing_periodic()
        self.assertFalse(cal.is_homing)
        self.assertTrue(self._motor_stopped)

    def test_optional_current_limit_skipped(self):
        """Test homing works without set_current_limit callback."""
        cbs = self._make_callbacks()
        del cbs['set_current_limit']
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0
        )
        self.assertTrue(cal.is_homing)
        self.assertIsNone(self._current_limit)

    # ---- Motor param with callback override ----

    def test_motor_param_with_callback_override(self):
        """Test that explicit callback overrides SparkMax default."""
        # Use CAN ID 41 motor from TestPositionCalibration class setup
        motor = rev.SparkMax(
            42, rev.SparkLowLevel.MotorType.kBrushless
        )
        custom_output = []
        cal = PositionCalibration(
            name="CbOverride",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            motor=motor,
            set_motor_output=lambda p: custom_output.append(p),
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.3,
            max_homing_time=5.0, homing_forward=True
        )
        cal._homing_periodic()
        # Custom callback should have been called, not motor.set()
        self.assertEqual(len(custom_output), 1)
        self.assertAlmostEqual(custom_output[0], 0.3, places=1)

    # ---- Abort with callbacks ----

    def test_abort_calls_stop_and_restore(self):
        """Test that abort fires stop_motor and restore_config callbacks."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True
        )
        self.assertIsNotNone(self._saved)
        self._motor_stopped = False
        self._restored = None

        cal.abort()

        self.assertTrue(self._motor_stopped)
        self.assertIsNotNone(self._restored)
        self.assertEqual(self._restored, {'marker': True})

    # ---- home_position parameter ----

    def test_homing_with_custom_home_position(self):
        """Test that home_position overrides the default 0.0 encoder value."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
            min_velocity=1.0, home_position=90.0
        )
        self._velocity = 0.0
        cal._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal._homing_periodic()

        self.assertAlmostEqual(self._position, 90.0, places=1)

    # ---- _load_from_nt memory-only soft limits ----

    def test_load_from_nt_no_hardware_soft_limits(self):
        """Test that _load_from_nt computes soft limits in memory but
        does NOT apply them to motor hardware."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        # Simulate persisting calibration data
        cal._is_calibrated = True
        cal._hard_limit_min = 0.0
        cal._hard_limit_max = 200.0
        cal._soft_limit_margin = 0.05
        cal._save_to_nt()

        # Reset soft limits tracker
        self._soft_limits = None

        # Create new instance — should load persisted data
        _calibration_classes.pop("CbTest", None)
        cal2 = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **self._make_callbacks()
        )
        # Soft limits should be computed in memory
        self.assertTrue(cal2.is_calibrated)
        self.assertAlmostEqual(cal2.min_soft_limit, 10.0, places=1)
        self.assertAlmostEqual(cal2.max_soft_limit, 190.0, places=1)
        # But NOT applied to hardware via set_soft_limits callback
        self.assertIsNone(self._soft_limits)

    def test_homing_applies_soft_limits_when_calibrated(self):
        """Test that after homing, if calibrated data exists, soft limits
        are applied to motor hardware."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        # Simulate persisting calibration data
        cal._is_calibrated = True
        cal._hard_limit_min = 0.0
        cal._hard_limit_max = 200.0
        cal._soft_limit_margin = 0.05
        cal._save_to_nt()

        # Reset soft limits tracker
        self._soft_limits = None

        # Create new instance — loads persisted data (memory only)
        _calibration_classes.pop("CbTest", None)
        cal2 = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **self._make_callbacks()
        )
        self.assertIsNone(self._soft_limits)

        # Now home — after homing completes, soft limits should
        # be applied to hardware
        cal2.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=False,
            min_velocity=1.0
        )
        self._velocity = 0.0
        cal2._homing_periodic()
        wpilib.simulation.stepTiming(0.15)
        cal2._homing_periodic()

        self.assertFalse(cal2.is_homing)
        self.assertIsNotNone(self._soft_limits)
        self.assertAlmostEqual(self._soft_limits[0], 10.0, places=1)
        self.assertAlmostEqual(self._soft_limits[1], 190.0, places=1)

    # ---- Valid callbacks constant ----

    def test_valid_callbacks_contains_all_expected(self):
        """Test that _VALID_CALLBACKS has the expected set of names."""
        expected = {
            'get_position', 'get_velocity', 'set_position',
            'set_motor_output', 'stop_motor',
            'set_current_limit', 'set_soft_limits', 'disable_soft_limits',
            'save_config', 'restore_config',
            'get_forward_limit_switch', 'get_reverse_limit_switch',
            'on_limit_detected',
        }
        self.assertEqual(_VALID_CALLBACKS, expected)

    # ---- get_callbacks() ----

    def test_get_callbacks_all_set(self):
        """Test get_callbacks returns all callbacks when fully configured."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        result = cal.get_callbacks()
        self.assertEqual(set(result.keys()), _VALID_CALLBACKS)
        for name, func in result.items():
            self.assertIsNotNone(func, f"{name} should be set")

    def test_get_callbacks_partial(self):
        """Test get_callbacks returns None for unset callbacks."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            set_motor_output=self._set_motor_output,
            stop_motor=self._stop_motor,
        )
        result = cal.get_callbacks()
        self.assertIsNotNone(result['set_motor_output'])
        self.assertIsNotNone(result['stop_motor'])
        self.assertIsNone(result['get_velocity'])
        self.assertIsNone(result['get_position'])

    def test_get_callbacks_reflects_set_callbacks(self):
        """Test get_callbacks updates after set_callbacks is called."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        self.assertIsNone(cal.get_callbacks()['get_velocity'])
        cal.set_callbacks(get_velocity=lambda: 0.0)
        self.assertIsNotNone(cal.get_callbacks()['get_velocity'])

    # ---- NT callback booleans ----

    def test_nt_callback_booleans_all_set(self):
        """Test NT booleans are True for all set callbacks."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        for cb_name in _VALID_CALLBACKS:
            value = getattr(cal, f'_nt_cb_{cb_name}')
            self.assertTrue(value, f"_nt_cb_{cb_name} should be True")

    def test_nt_callback_booleans_partial(self):
        """Test NT booleans are False for unset callbacks."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            set_motor_output=self._set_motor_output,
            stop_motor=self._stop_motor,
            get_velocity=lambda: 0.0,
        )
        self.assertTrue(cal._nt_cb_set_motor_output)
        self.assertTrue(cal._nt_cb_stop_motor)
        self.assertTrue(cal._nt_cb_get_velocity)
        self.assertFalse(cal._nt_cb_get_position)
        self.assertFalse(cal._nt_cb_save_config)

    def test_nt_callback_booleans_update_on_set_callbacks(self):
        """Test NT booleans update when set_callbacks is called."""
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
        )
        self.assertFalse(cal._nt_cb_get_velocity)
        cal.set_callbacks(get_velocity=lambda: 0.0)
        self.assertTrue(cal._nt_cb_get_velocity)

    # ---- Clearing callbacks ----

    def test_clear_callback_with_none(self):
        """Test that passing None to set_callbacks clears a callback."""
        cbs = self._make_callbacks()
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            **cbs
        )
        self.assertIsNotNone(cal.get_callbacks()['get_forward_limit_switch'])
        cal.set_callbacks(get_forward_limit_switch=None)
        self.assertIsNone(cal.get_callbacks()['get_forward_limit_switch'])

    def test_clear_limit_switches_from_motor_config(self):
        """Test clearing auto-assigned limit switches from motor= config.

        When using motor= to create a PositionCalibration, limit switch
        callbacks are auto-assigned. If the mechanism has no limit
        switches, clear them before homing so stall detection is used
        instead.
        """
        motor = rev.SparkMax(
            43, rev.SparkLowLevel.MotorType.kBrushless
        )
        cal = PositionCalibration(
            name="CbTest",
            fallback_min=self.MIN_SOFT_LIMIT,
            fallback_max=self.MAX_SOFT_LIMIT,
            motor=motor,
        )
        # Limit switches are auto-assigned by SparkMaxCallbacks
        self.assertIsNotNone(
            cal.get_callbacks()['get_forward_limit_switch'])
        self.assertIsNotNone(
            cal.get_callbacks()['get_reverse_limit_switch'])

        # Clear them for a mechanism with no limit switches
        cal.set_callbacks(
            get_forward_limit_switch=None,
            get_reverse_limit_switch=None,
        )
        self.assertIsNone(
            cal.get_callbacks()['get_forward_limit_switch'])
        self.assertIsNone(
            cal.get_callbacks()['get_reverse_limit_switch'])
        # NT booleans should update too
        self.assertFalse(cal._nt_cb_get_forward_limit_switch)
        self.assertFalse(cal._nt_cb_get_reverse_limit_switch)

        # Homing should still work via stall detection (get_velocity)
        self.assertIsNotNone(cal.get_callbacks()['get_velocity'])
        cal.homing_init(
            max_current=10.0, max_power_pct=0.2,
            max_homing_time=5.0, homing_forward=True,
        )
        self.assertTrue(cal.is_homing)


if __name__ == "__main__":
    unittest.main()
