"""
Integration tests for the vision simulation pipeline.

Tests verify that VisionSystemSim generates AprilTag detections that flow
through Localization's filtering and into the drivetrain pose estimator.

These tests use real PhotonCamera + VisionSystemSim objects (not mocks)
to exercise the full vision pipeline in simulation.

Generated by Claude.
"""

import math
import unittest
from unittest.mock import MagicMock

import wpilib
import wpilib.simulation
from wpimath.geometry import Pose2d, Rotation2d

from config import OperatorRobotConfig
from subsystem.localization.localization import Localization


class TestVisionSim(unittest.TestCase):
    """Integration tests using a shared Localization instance to avoid
    PhotonCamera UDP port conflicts across tests."""

    @classmethod
    def setUpClass(cls):
        """Create a single Localization + VisionSystemSim shared by all tests."""
        wpilib.simulation.pauseTiming()
        cls.drivetrain = MagicMock()
        cls.drivetrain.current_yaw.return_value = Rotation2d()
        cls.drivetrain.add_vision_pose_estimate = MagicMock()

        cls.loc = Localization(cls.drivetrain)
        cls.loc.setup_sim()

        # Load the field layout for tag lookups
        from robotpy_apriltag import AprilTagField, AprilTagFieldLayout
        cls.field_layout = AprilTagFieldLayout.loadField(
            AprilTagField.kDefaultField
        )

    @classmethod
    def tearDownClass(cls):
        wpilib.simulation.restartTiming()

    def setUp(self):
        """Reset mock call tracking and counters before each test."""
        self.drivetrain.add_vision_pose_estimate.reset_mock()
        self.loc._accepted_count = 0
        self.loc._rejected_count = 0

    def _run_sim_cycle(self, robot_pose, gyro_yaw_deg=None):
        """Feed a pose into the sim and process results."""
        if gyro_yaw_deg is not None:
            self.drivetrain.current_yaw.return_value = Rotation2d.fromDegrees(
                gyro_yaw_deg
            )
        else:
            self.drivetrain.current_yaw.return_value = robot_pose.rotation()

        self.loc.update_sim(robot_pose)
        wpilib.simulation.stepTiming(0.05)
        self.loc.update()

    def test_detects_nearby_tag(self):
        """Robot placed near AprilTag 1 should produce a vision measurement."""
        tag1_pose = self.field_layout.getTagPose(1)
        self.assertIsNotNone(tag1_pose)

        tag_2d = tag1_pose.toPose2d()
        robot_x = tag_2d.X() + 1.5 * math.cos(tag_2d.rotation().radians())
        robot_y = tag_2d.Y() + 1.5 * math.sin(tag_2d.rotation().radians())
        angle_to_tag = math.atan2(
            tag_2d.Y() - robot_y, tag_2d.X() - robot_x
        )
        robot_pose = Pose2d(robot_x, robot_y, Rotation2d(angle_to_tag))

        self._run_sim_cycle(robot_pose, gyro_yaw_deg=math.degrees(angle_to_tag))

        if self.drivetrain.add_vision_pose_estimate.called:
            call_args = self.drivetrain.add_vision_pose_estimate.call_args
            vision_pose = call_args[0][0]
            dist = robot_pose.translation().distance(vision_pose.translation())
            self.assertLess(
                dist, 1.0,
                f"Vision pose too far from actual: {dist:.2f}m"
            )

    def test_sim_pipeline_does_not_crash(self):
        """Running multiple sim + update cycles should not crash."""
        robot_pose = Pose2d(4.0, 4.0, Rotation2d())

        for _ in range(10):
            self._run_sim_cycle(robot_pose, gyro_yaw_deg=0.0)

    def test_counters_update(self):
        """After processing, accepted + rejected should be non-negative."""
        robot_pose = Pose2d(4.0, 4.0, Rotation2d())
        self._run_sim_cycle(robot_pose, gyro_yaw_deg=0.0)

        total = self.loc._accepted_count + self.loc._rejected_count
        self.assertGreaterEqual(total, 0)

    def test_multi_tag_produces_tighter_std_devs(self):
        """When multiple tags are visible, std devs should use multi-tag base."""
        tag6 = self.field_layout.getTagPose(6)
        tag7 = self.field_layout.getTagPose(7)
        if tag6 is None or tag7 is None:
            self.skipTest("Tags 6/7 not in field layout")

        mid_x = (tag6.X() + tag7.X()) / 2
        mid_y = (tag6.Y() + tag7.Y()) / 2
        robot_pose = Pose2d(mid_x + 1.5, mid_y, Rotation2d.fromDegrees(180.0))

        self._run_sim_cycle(robot_pose, gyro_yaw_deg=180.0)

        if self.drivetrain.add_vision_pose_estimate.called:
            call_args = self.drivetrain.add_vision_pose_estimate.call_args
            std_devs = call_args[0][2]
            cfg = OperatorRobotConfig
            self.assertLessEqual(
                std_devs[0], cfg.vision_single_tag_std_devs[0],
                f"X std dev {std_devs[0]} should be <= single-tag base"
            )
