"""
Unit tests for the Localization vision filtering and standard deviation logic.

Tests validate:
- Field bounds filtering (rejects poses outside field)
- Z-height filtering (rejects poses above carpet)
- Single-tag ambiguity filtering
- Gyro rotation agreement filtering
- Dynamic standard deviation computation (single-tag vs multi-tag)
- Distance-based std dev scaling
- Single-tag distance rejection

Generated by Claude.
"""

import math
from unittest.mock import MagicMock

from wpimath.geometry import Pose3d, Rotation2d, Rotation3d, Translation3d
from robotpy_apriltag import AprilTagField, AprilTagFieldLayout

from config import OperatorRobotConfig
from subsystem.localization.localization import Localization, FIELD_LENGTH_M, FIELD_WIDTH_M


def _make_localization(gyro_yaw_deg=0.0):
    """Create a Localization with a mocked drivetrain and no real cameras."""
    drivetrain = MagicMock()
    drivetrain.current_yaw.return_value = Rotation2d.fromDegrees(gyro_yaw_deg)
    drivetrain.add_vision_pose_estimate = MagicMock()

    loc = Localization.__new__(Localization)
    loc.drivetrain = drivetrain
    loc.field_layout = AprilTagFieldLayout.loadField(
        AprilTagField.kDefaultField
    )
    loc.cameras = []
    loc._accepted_count = 0
    loc._rejected_count = 0

    cfg = OperatorRobotConfig
    loc.ambiguity_threshold = cfg.vision_ambiguity_threshold
    loc.single_tag_max_dist = cfg.vision_single_tag_max_distance_m
    loc.field_border_margin = cfg.vision_field_border_margin_m
    loc.max_z_error = cfg.vision_max_z_error_m
    loc.max_rotation_error_rad = math.radians(cfg.vision_max_rotation_error_deg)
    loc.single_tag_std_devs = cfg.vision_single_tag_std_devs
    loc.multi_tag_std_devs = cfg.vision_multi_tag_std_devs
    loc.std_dev_distance_factor = cfg.vision_std_dev_distance_factor

    # Populate tag caches (mirrors Localization.__init__)
    loc._tag_pose_cache = {}
    loc._tag_translation_cache = {}
    for tag_id in range(1, 23):
        pose = loc.field_layout.getTagPose(tag_id)
        if pose is not None:
            loc._tag_pose_cache[tag_id] = pose
            loc._tag_translation_cache[tag_id] = (
                pose.toPose2d().translation()
            )

    return loc


def _make_target(fiducial_id=1, ambiguity=0.0):
    """Create a mock PhotonTrackedTarget."""
    target = MagicMock()
    target.fiducialId = fiducial_id
    target.poseAmbiguity = ambiguity
    return target


def _pose3d(x=8.0, y=4.0, z=0.0, yaw_deg=0.0):
    """Create a Pose3d at the given position."""
    return Pose3d(
        Translation3d(x, y, z),
        Rotation3d(0, 0, math.radians(yaw_deg)),
    )


# ── Field Bounds Filter ──


class TestFieldBoundsFilter:

    def test_pose_inside_field_passes(self):
        loc = _make_localization()
        pose = _pose3d(x=8.0, y=4.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_at_origin_passes(self):
        loc = _make_localization()
        pose = _pose3d(x=0.0, y=0.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_negative_x_beyond_margin_rejected(self):
        loc = _make_localization()
        margin = loc.field_border_margin
        pose = _pose3d(x=-(margin + 0.1), y=4.0)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_beyond_field_length_rejected(self):
        loc = _make_localization()
        margin = loc.field_border_margin
        pose = _pose3d(x=FIELD_LENGTH_M + margin + 0.1, y=4.0)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_negative_y_beyond_margin_rejected(self):
        loc = _make_localization()
        margin = loc.field_border_margin
        pose = _pose3d(x=8.0, y=-(margin + 0.1))
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_beyond_field_width_rejected(self):
        loc = _make_localization()
        margin = loc.field_border_margin
        pose = _pose3d(x=8.0, y=FIELD_WIDTH_M + margin + 0.1)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_pose_within_margin_passes(self):
        """A pose slightly outside the field but within margin should pass."""
        loc = _make_localization()
        margin = loc.field_border_margin
        pose = _pose3d(x=-(margin - 0.1), y=4.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)


# ── Z-Height Filter ──


class TestZHeightFilter:

    def test_zero_z_passes(self):
        loc = _make_localization()
        pose = _pose3d(z=0.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_small_z_passes(self):
        loc = _make_localization()
        pose = _pose3d(z=0.1)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_high_z_rejected(self):
        loc = _make_localization()
        pose = _pose3d(z=loc.max_z_error + 0.1)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_negative_z_rejected(self):
        loc = _make_localization()
        pose = _pose3d(z=-(loc.max_z_error + 0.1))
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)


# ── Ambiguity Filter ──


class TestAmbiguityFilter:

    def test_low_ambiguity_single_tag_passes(self):
        loc = _make_localization()
        target = _make_target(ambiguity=0.05)
        assert loc._passes_filters(_pose3d(), [target], is_multi_tag=False)

    def test_high_ambiguity_single_tag_rejected(self):
        loc = _make_localization()
        target = _make_target(ambiguity=0.5)
        assert not loc._passes_filters(_pose3d(), [target], is_multi_tag=False)

    def test_ambiguity_at_threshold_rejected(self):
        loc = _make_localization()
        target = _make_target(ambiguity=loc.ambiguity_threshold + 0.01)
        assert not loc._passes_filters(_pose3d(), [target], is_multi_tag=False)

    def test_multi_tag_ignores_ambiguity(self):
        """Multi-tag results should pass even with high individual target ambiguity."""
        loc = _make_localization()
        target = _make_target(ambiguity=0.9)
        assert loc._passes_filters(_pose3d(), [target], is_multi_tag=True)


# ── Rotation Agreement Filter ──


class TestRotationFilter:

    def test_matching_rotation_passes(self):
        loc = _make_localization(gyro_yaw_deg=45.0)
        pose = _pose3d(yaw_deg=45.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_small_rotation_diff_passes(self):
        loc = _make_localization(gyro_yaw_deg=0.0)
        pose = _pose3d(yaw_deg=10.0)
        assert loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_large_rotation_diff_rejected(self):
        loc = _make_localization(gyro_yaw_deg=0.0)
        max_deg = OperatorRobotConfig.vision_max_rotation_error_deg
        pose = _pose3d(yaw_deg=max_deg + 10.0)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)

    def test_opposite_heading_rejected(self):
        loc = _make_localization(gyro_yaw_deg=0.0)
        pose = _pose3d(yaw_deg=180.0)
        assert not loc._passes_filters(pose, [_make_target()], is_multi_tag=True)


# ── Dynamic Standard Deviations ──


class TestStdDevComputation:

    def test_multi_tag_uses_multi_tag_base(self):
        loc = _make_localization()
        # Use tag IDs that exist in the field layout; place estimated pose
        # very close to a real tag so distance scaling is ~1.0
        tag_pose = loc.field_layout.getTagPose(1)
        assert tag_pose is not None
        estimated = Pose3d(
            tag_pose.translation(), Rotation3d()
        )
        target_ids = [1, 2]
        std_devs = loc._compute_std_devs(estimated, target_ids)
        # At distance ~0 with 2 tags, should be close to multi-tag base
        for i in range(3):
            # Allow some tolerance for distance not being exactly 0
            assert std_devs[i] < loc.single_tag_std_devs[i] or loc.single_tag_std_devs[i] == float('inf')

    def test_single_tag_uses_single_tag_base(self):
        loc = _make_localization()
        tag_pose = loc.field_layout.getTagPose(1)
        assert tag_pose is not None
        estimated = Pose3d(
            tag_pose.translation(), Rotation3d()
        )
        target_ids = [1]
        std_devs = loc._compute_std_devs(estimated, target_ids)
        # Single tag theta should be inf
        assert std_devs[2] == float('inf')

    def test_single_tag_beyond_max_distance_returns_inf(self):
        loc = _make_localization()
        # Place estimated pose very far from any tag
        estimated = _pose3d(x=0.0, y=0.0)
        # Use a tag that's far away (tag 1 is on the far side of the field)
        # Just need avg_dist > single_tag_max_dist
        target_ids = [1]
        tag_pose = loc.field_layout.getTagPose(1)
        assert tag_pose is not None
        dist = tag_pose.toPose2d().translation().distance(
            estimated.toPose2d().translation()
        )
        if dist <= loc.single_tag_max_dist:
            # Move estimated pose further away to ensure rejection
            estimated = _pose3d(x=-10.0, y=-10.0)
        std_devs = loc._compute_std_devs(estimated, target_ids)
        assert all(s == float('inf') for s in std_devs)

    def test_std_devs_increase_with_distance(self):
        loc = _make_localization()
        tag_pose = loc.field_layout.getTagPose(1)
        assert tag_pose is not None

        targets_multi = [1, 2]

        # Close estimate
        close_pose = Pose3d(tag_pose.translation(), Rotation3d())
        close_std = loc._compute_std_devs(close_pose, targets_multi)

        # Far estimate (2m away from tag)
        far_translation = Translation3d(
            tag_pose.X() + 2.0, tag_pose.Y(), tag_pose.Z()
        )
        far_pose = Pose3d(far_translation, Rotation3d())
        far_std = loc._compute_std_devs(far_pose, targets_multi)

        # Far should have larger std devs than close
        assert far_std[0] > close_std[0]
        assert far_std[1] > close_std[1]

    def test_no_tags_returns_single_tag_base(self):
        loc = _make_localization()
        # Empty target list
        std_devs = loc._compute_std_devs(_pose3d(), [])
        assert std_devs == loc.single_tag_std_devs

    def test_unknown_tag_id_returns_single_tag_base(self):
        loc = _make_localization()
        # Tag ID that doesn't exist in the field layout
        target_ids = [999]
        std_devs = loc._compute_std_devs(_pose3d(), target_ids)
        assert std_devs == loc.single_tag_std_devs

    def test_distance_scaling_formula(self):
        """Verify the quadratic scaling formula directly."""
        loc = _make_localization()
        tag_pose = loc.field_layout.getTagPose(1)
        assert tag_pose is not None

        # Place estimate exactly at tag position
        estimated = Pose3d(tag_pose.translation(), Rotation3d())
        target_ids = [1, 2]

        std_devs = loc._compute_std_devs(estimated, target_ids)

        # tag 2 should be at a different position, so avg_dist > 0
        tag2_pose = loc.field_layout.getTagPose(2)
        if tag2_pose is not None:
            dist1 = tag_pose.toPose2d().translation().distance(
                estimated.toPose2d().translation()
            )
            dist2 = tag2_pose.toPose2d().translation().distance(
                estimated.toPose2d().translation()
            )
            avg_dist = (dist1 + dist2) / 2.0
            expected_scale = 1.0 + (avg_dist ** 2 / loc.std_dev_distance_factor)
            for i in range(2):  # x and y
                expected = loc.multi_tag_std_devs[i] * expected_scale
                assert abs(std_devs[i] - expected) < 0.001
