"""
Unit tests for the PassiveRangeFinderCommand.

Tests validate:
- Coast mode set on start, original idle mode restored on stop
- Conversion factor set to 1.0 during run, computed from range on stop
- Encoder zeroed at start of calibration
- Min/max tracking updates correctly
- End always applies discovered range as soft limits
- zero_on_end and full_range options

Generated by Claude.
"""

import unittest

import rev
import wpilib
import wpilib.simulation
from commands2 import Subsystem
from wpimath.system.plant import DCMotor

from utils.passive_range_finder import PassiveRangeFinderCommand


class TestPassiveRangeFinder(unittest.TestCase):
    """Test suite for PassiveRangeFinderCommand."""

    MOTOR_CAN_ID = 18
    POSITION_CONVERSION_FACTOR = 360.0 / 1.7

    @classmethod
    def setUpClass(cls):
        wpilib.simulation.pauseTiming()
        cls.motor = rev.SparkMax(
            cls.MOTOR_CAN_ID,
            rev.SparkLowLevel.MotorType.kBrushless
        )
        cls.subsystem = Subsystem()
        cls.motor_sim = rev.SparkSim(cls.motor, DCMotor.NEO())
        cls.motor_sim.setBusVoltage(12.0)

        # Configure motor with known settings
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kBrake)
        (
            cfg.encoder
            .positionConversionFactor(cls.POSITION_CONVERSION_FACTOR)
            .velocityConversionFactor(cls.POSITION_CONVERSION_FACTOR / 60.0)
        )
        cls.motor.configure(
            cfg,
            rev.ResetMode.kResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )

    @classmethod
    def tearDownClass(cls):
        """Free the SparkMax so other test classes can reuse the CAN ID."""
        import gc
        del cls.motor_sim
        del cls.motor
        gc.collect()

    def setUp(self):
        # Restore known config before each test
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kBrake)
        (
            cfg.encoder
            .positionConversionFactor(self.POSITION_CONVERSION_FACTOR)
            .velocityConversionFactor(self.POSITION_CONVERSION_FACTOR / 60.0)
        )
        self.motor.configure(
            cfg,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        self.motor_sim.getRelativeEncoderSim().setPosition(0.0)
        self.cmd = PassiveRangeFinderCommand(
            self.motor, "TestHood", self.subsystem)

    # -- Initialize tests --

    def test_initialize_sets_coast_mode(self):
        self.cmd.initialize()
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kCoast)
        self.cmd.end(True)

    def test_initialize_sets_conversion_factor_to_one(self):
        self.cmd.initialize()
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - 1.0) < 0.01
        self.cmd.end(True)

    def test_initialize_zeros_encoder(self):
        self.motor_sim.getRelativeEncoderSim().setPosition(5.0)
        self.cmd.initialize()
        assert abs(self.cmd._min_raw) < 0.01
        assert abs(self.cmd._max_raw) < 0.01
        self.cmd.end(True)

    # -- Execute tests --

    def test_execute_tracks_max(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.cmd.execute()
        assert abs(self.cmd._max_raw - 10.0) < 0.01
        self.cmd.end(True)

    def test_execute_tracks_min(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(-3.0)
        self.cmd.execute()
        assert abs(self.cmd._min_raw - (-3.0)) < 0.01
        self.cmd.end(True)

    def test_execute_tracks_both(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(10.0)
        self.cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(-5.0)
        self.cmd.execute()
        assert abs(self.cmd._max_raw - 10.0) < 0.01
        assert abs(self.cmd._min_raw - (-5.0)) < 0.01
        self.cmd.end(True)

    # -- End tests --

    def test_end_computes_normalized_conversion_factor(self):
        """Without full_range, conversion factor = 1/range (0..1)."""
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(0.5)
        self.cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(-0.5)
        self.cmd.execute()
        self.cmd.end(False)
        # range = 1.0, so cf = 1/1.0 = 1.0
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - 1.0) < 0.01

    def test_end_computes_full_range_conversion_factor(self):
        """With full_range=20, conversion factor = 20/range."""
        cmd = PassiveRangeFinderCommand(
            self.motor, "TestHood", self.subsystem, full_range=20.0)
        cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(2.0)
        cmd.execute()
        cmd.end(False)
        # range = 2.0, cf = 20/2.0 = 10.0
        cf = self.motor.configAccessor.encoder.getPositionConversionFactor()
        assert abs(cf - 10.0) < 0.01

    def test_end_restores_idle_mode(self):
        self.cmd.initialize()
        self.cmd.end(False)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kBrake)

    def test_end_applies_soft_limits(self):
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(0.2)
        self.cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(-0.1)
        self.cmd.execute()
        self.cmd.end(False)

        sl = self.motor.configAccessor.softLimit
        assert sl.getForwardSoftLimitEnabled()
        assert sl.getReverseSoftLimitEnabled()
        # range=0.3, cf=1/0.3=3.333
        # fwd=0.2*cf=0.667, rev=-0.1*cf=-0.333
        cf = 1.0 / 0.3
        expected_fwd = 0.2 * cf
        expected_rev = -0.1 * cf
        assert abs(sl.getForwardSoftLimit() - expected_fwd) < 0.1
        assert abs(sl.getReverseSoftLimit() - expected_rev) < 0.1

    def test_interrupted_still_applies_limits(self):
        """toggleOnTrue cancels with interrupted=True, limits still apply."""
        self.cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(0.5)
        self.cmd.execute()
        self.cmd.end(True)

        sl = self.motor.configAccessor.softLimit
        assert sl.getForwardSoftLimitEnabled()
        assert sl.getReverseSoftLimitEnabled()

    def test_interrupted_restores_idle_mode(self):
        self.cmd.initialize()
        self.cmd.end(True)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kBrake)

    # -- isFinished --

    def test_is_finished_returns_false(self):
        assert not self.cmd.isFinished()

    # -- Coast mode restore for originally coast motor --

    def test_coast_motor_stays_coast(self):
        """If motor was originally coast, it should stay coast after end."""
        cfg = rev.SparkMaxConfig()
        cfg.setIdleMode(rev.SparkBaseConfig.IdleMode.kCoast)
        self.motor.configure(
            cfg,
            rev.ResetMode.kNoResetSafeParameters,
            rev.PersistMode.kNoPersistParameters
        )
        cmd = PassiveRangeFinderCommand(
            self.motor, "TestCoast", self.subsystem)
        cmd.initialize()
        cmd.end(False)
        assert (self.motor.configAccessor.getIdleMode()
                == rev.SparkBaseConfig.IdleMode.kCoast)

    # -- zero_on_end tests --

    def test_zero_on_end_zeros_encoder(self):
        cmd = PassiveRangeFinderCommand(
            self.motor, "TestHood", self.subsystem, zero_on_end=True)
        cmd.initialize()
        self.motor_sim.getRelativeEncoderSim().setPosition(1.0)
        cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(0.5)
        cmd.end(False)
        # Encoder should be zeroed after end
        pos = self.motor.getEncoder().getPosition()
        assert abs(pos) < 0.01

    def test_zero_on_end_offsets_limits(self):
        cmd = PassiveRangeFinderCommand(
            self.motor, "TestHood", self.subsystem,
            zero_on_end=True, full_range=20.0)
        cmd.initialize()
        # Move to 2.0 (max), then back to 1.0 (end position)
        self.motor_sim.getRelativeEncoderSim().setPosition(2.0)
        cmd.execute()
        self.motor_sim.getRelativeEncoderSim().setPosition(1.0)
        cmd.end(False)

        sl = self.motor.configAccessor.softLimit
        # range=2.0, cf=20/2=10
        # fwd_raw=2.0-1.0=1.0, rev_raw=0.0-1.0=-1.0
        # fwd_scaled=1.0*10=10, rev_scaled=-1.0*10=-10
        assert abs(sl.getForwardSoftLimit() - 10.0) < 0.5
        assert abs(sl.getReverseSoftLimit() - (-10.0)) < 0.5
