"""
System tests: robot survives subsystem creation failures.
Generated by Claude.

Verifies the robot can cycle through disabled → autonomous → teleop
when swerve module or drivetrain creation throws an exception.

Uses the real SubsystemRegistry with mock subsystem creators that
mirror the swerve module → drivetrain → turret topology. After the
registry handles creation failures, the test simulates the full
robot lifecycle (the same calls RobotSwerve makes in each mode).
"""

import unittest
from unittest.mock import MagicMock, patch

import wpilib
import wpilib.simulation

from constants import RobotConstants
from utils.subsystem_factory import (
    SubsystemEntry,
    SubsystemRegistry,
    SubsystemState,
    _registry_state_classes,
)


def _make_mock_subsystem(name):
    """Create a mock subsystem with common lifecycle methods."""
    sub = MagicMock()
    sub.name = name
    return sub


def _failing_creator(subs):
    """Creator that simulates a hardware failure."""
    raise RuntimeError("CAN bus timeout — simulated hardware failure")


def _build_swerve_manifest(
    module_creators=None,
    drivetrain_creator=None,
    turret_creator=None,
):
    """
    Build a manifest matching the real robot topology:
    4 swerve modules (enabled) → drivetrain (enabled, depends on modules) → turret (enabled, independent).

    Any creator can be replaced to inject failures.
    """
    module_names = [
        "swerve_module_frontLeft",
        "swerve_module_frontRight",
        "swerve_module_backLeft",
        "swerve_module_backRight",
    ]

    if module_creators is None:
        module_creators = [
            lambda subs, n=n: _make_mock_subsystem(n)
            for n in module_names
        ]
    if drivetrain_creator is None:
        drivetrain_creator = lambda subs: _make_mock_subsystem("drivetrain")
    if turret_creator is None:
        turret_creator = lambda subs: _make_mock_subsystem("turret")

    entries = [
        SubsystemEntry(
            name=name,
            default_state=SubsystemState.enabled,
            creator=creator,
        )
        for name, creator in zip(module_names, module_creators)
    ]
    entries.append(SubsystemEntry(
        name="drivetrain",
        default_state=SubsystemState.enabled,
        creator=drivetrain_creator,
        dependencies=module_names,
    ))
    entries.append(SubsystemEntry(
        name="turret",
        default_state=SubsystemState.enabled,
        creator=turret_creator,
    ))

    return entries


def _make_registry(entries):
    """Create a SubsystemRegistry with NT state mocked to use default states."""
    holders = {}

    def get_holder(name):
        if name not in holders:
            h = MagicMock()
            h.state = ""  # empty → use default_state
            holders[name] = h
        return holders[name]

    with patch(
        "utils.subsystem_factory._get_state_holder",
        side_effect=get_holder,
    ):
        return SubsystemRegistry(entries)


def _simulate_robot_lifecycle(registry):
    """
    Simulate the robot cycling through all modes, calling the same
    registry lifecycle methods that RobotSwerve and robot.py invoke.

    Calls:
      disabledInit → (robotPeriodic) →
      autonomousInit → autonomousPeriodic (10 cycles with robotPeriodic) →
      teleopInit → teleopPeriodic (10 cycles with robotPeriodic) →
      disabledInit
    """
    # --- disabled ---
    registry.run_all_disabled_init()
    registry.run_all_telemetry()

    # --- autonomous ---
    # autonomousInit: RobotSwerve selects auto command (no registry call)
    for _ in range(10):
        registry.run_all_telemetry()

    # --- teleop ---
    registry.run_all_teleop_init()
    for _ in range(10):
        registry.run_all_telemetry()
        registry.run_all_teleop_periodic()

    # --- back to disabled ---
    registry.run_all_disabled_init()
    registry.run_all_telemetry()


class TestRobotDegradedSwerveModule(unittest.TestCase):
    """
    Robot lifecycle when a swerve module fails to create.
    Generated by Claude.
    """

    def setUp(self):
        _registry_state_classes.clear()

    def test_one_module_fails_robot_cycles(self):
        """
        One swerve module throws during creation. The drivetrain is
        skipped (missing dependency), but the turret and other modules
        are created. Robot cycles through all modes without crashing.
        """
        module_creators = [
            _failing_creator,                                  # frontLeft fails
            lambda subs: _make_mock_subsystem("frontRight"),
            lambda subs: _make_mock_subsystem("backLeft"),
            lambda subs: _make_mock_subsystem("backRight"),
        ]
        entries = _build_swerve_manifest(module_creators=module_creators)
        registry = _make_registry(entries)

        # Failed module → None, drivetrain skipped, turret still alive
        self.assertIsNone(registry.get("swerve_module_frontLeft"))
        self.assertIsNone(registry.get("drivetrain"))
        self.assertIsNotNone(registry.get("turret"))

        # Full lifecycle — must not raise
        _simulate_robot_lifecycle(registry)

    def test_all_modules_fail_robot_cycles(self):
        """
        All 4 swerve modules throw during creation. Drivetrain is
        skipped. Turret still works. Robot cycles without crashing.
        """
        entries = _build_swerve_manifest(
            module_creators=[_failing_creator] * 4,
        )
        registry = _make_registry(entries)

        self.assertIsNone(registry.get("drivetrain"))
        self.assertIsNotNone(registry.get("turret"))

        _simulate_robot_lifecycle(registry)


class TestRobotDegradedDrivetrain(unittest.TestCase):
    """
    Robot lifecycle when the drivetrain itself fails to create.
    Generated by Claude.
    """

    def setUp(self):
        _registry_state_classes.clear()

    def test_drivetrain_fails_robot_cycles(self):
        """
        All modules succeed but the drivetrain throws (e.g. gyro init
        failure). Modules and turret remain. Robot cycles without crashing.
        """
        entries = _build_swerve_manifest(
            drivetrain_creator=_failing_creator,
        )
        registry = _make_registry(entries)

        # All modules created, drivetrain failed, turret still alive
        self.assertIsNotNone(registry.get("swerve_module_frontLeft"))
        self.assertIsNone(registry.get("drivetrain"))
        self.assertIsNotNone(registry.get("turret"))

        _simulate_robot_lifecycle(registry)

    def test_drivetrain_fails_active_subsystems_correct(self):
        """
        active_subsystems excludes the failed drivetrain and includes
        all other successfully created subsystems.
        """
        entries = _build_swerve_manifest(
            drivetrain_creator=_failing_creator,
        )
        registry = _make_registry(entries)

        active = registry.active_subsystems
        self.assertNotIn("drivetrain", active)
        self.assertIn("swerve_module_frontLeft", active)
        self.assertIn("turret", active)


class TestRobotDegradedAll(unittest.TestCase):
    """
    Robot lifecycle when all subsystems fail to create.
    Generated by Claude.
    """

    def setUp(self):
        _registry_state_classes.clear()

    def test_everything_fails_robot_still_cycles(self):
        """
        Every subsystem throws during creation. The robot has no
        active subsystems but can still cycle through all modes.
        """
        entries = _build_swerve_manifest(
            module_creators=[_failing_creator] * 4,
            drivetrain_creator=_failing_creator,
            turret_creator=_failing_creator,
        )
        registry = _make_registry(entries)

        self.assertEqual(len(registry.active_subsystems), 0)

        # Must not raise
        _simulate_robot_lifecycle(registry)


class TestRobotSwerveLifecycleNoDrivetrain(unittest.TestCase):
    """
    Test that RobotSwerve's mode handlers work when drivetrain is None.
    Generated by Claude.
    """

    def _make_container(self):
        """
        Build a minimal RobotSwerve-like object with the same mode
        handler logic but without needing the full HAL/hardware stack.
        """
        from robotswerve import RobotSwerve

        container = object.__new__(RobotSwerve)
        container.drivetrain = None
        container.auto_command = None
        container.auto_chooser = None
        container.teleop_stem_paths = {}
        container.teleop_auto_command = None
        container.enableTelemetry = False
        container.telemetry = None

        # Mock registry with no active subsystems
        container.registry = MagicMock(spec=SubsystemRegistry)

        return container

    def test_autonomous_init_no_drivetrain(self):
        """autonomousInit does not crash when drivetrain is None."""
        container = self._make_container()
        container.autonomousInit()

    def test_autonomous_periodic_no_drivetrain(self):
        """autonomousPeriodic does not crash when drivetrain is None."""
        container = self._make_container()
        container.autonomousPeriodic()

    def test_teleop_init_no_drivetrain(self):
        """teleopInit does not crash when drivetrain is None."""
        container = self._make_container()
        container.teleopInit()

    def test_teleop_periodic_no_drivetrain(self):
        """teleopPeriodic does not crash when drivetrain is None."""
        container = self._make_container()
        container.teleopPeriodic()

    def test_robot_periodic_no_drivetrain(self):
        """robotPeriodic does not crash when drivetrain is None."""
        container = self._make_container()
        container.robotPeriodic()

    def test_disabled_init_no_drivetrain(self):
        """disabledInit does not crash when drivetrain is None."""
        container = self._make_container()
        container.disabledInit()

    def test_test_init_no_drivetrain(self):
        """testInit does not crash when drivetrain is None."""
        container = self._make_container()
        # testInit calls CommandScheduler which needs WPILib — just verify no AttributeError
        try:
            container.testInit()
        except Exception:
            # CommandScheduler may not be initialized in test context; that's OK.
            # We only care that drivetrain=None doesn't cause a crash.
            pass

    def test_full_mode_cycle_no_drivetrain(self):
        """
        Simulate a full match cycle: disabled → auto → teleop → disabled.
        No crashes when drivetrain is None.
        """
        container = self._make_container()

        container.disabledInit()
        container.disabledPeriodic()
        container.robotPeriodic()

        container.autonomousInit()
        for _ in range(10):
            container.autonomousPeriodic()
            container.robotPeriodic()

        container.teleopInit()
        for _ in range(10):
            container.teleopPeriodic()
            container.robotPeriodic()

        container.disabledInit()
        container.disabledPeriodic()


class _OverrunHarness:
    """
    Minimal harness that replicates MyRobot's overrun detection logic.
    Avoids instantiating the real TimedCommandRobot C++ base class.
    """

    def __init__(self):
        self.overrun_alert = wpilib.Alert(
            "Loop overrun test", wpilib.Alert.AlertType.kWarning
        )
        self.overrun_count = 0
        self.loop_timer = wpilib.Timer()
        self.loop_timer.start()
        self.container = MagicMock()

    def robotPeriodic(self):
        """Same overrun check as MyRobot.robotPeriodic."""
        # Simulate container work (no-op via mock)
        self.container.robotPeriodic()

        period = RobotConstants.kPeriodicPeriodSec
        overran = self.loop_timer.hasElapsed(period)
        if overran:
            self.overrun_count += 1
        self.overrun_alert.set(overran)
        self.loop_timer.reset()


class TestLoopOverrun(unittest.TestCase):
    """
    Test that loop overrun detection works using wpilib.Timer.
    Generated by Claude.

    Uses sim timing control to advance FPGA time past the loop period
    and verify the overrun alert and counter respond correctly.
    """

    @classmethod
    def setUpClass(cls):
        wpilib.simulation.pauseTiming()

    def setUp(self):
        wpilib.simulation.restartTiming()
        wpilib.simulation.pauseTiming()

    def test_no_overrun_within_period(self):
        """No overrun when loop completes within the period."""
        harness = _OverrunHarness()
        period = RobotConstants.kPeriodicPeriodSec

        wpilib.simulation.stepTiming(period * 0.5)
        harness.robotPeriodic()

        self.assertEqual(harness.overrun_count, 0)

    def test_overrun_detected(self):
        """Overrun detected when FPGA time exceeds the loop period."""
        harness = _OverrunHarness()
        period = RobotConstants.kPeriodicPeriodSec

        wpilib.simulation.stepTiming(period * 2)
        harness.robotPeriodic()

        self.assertEqual(harness.overrun_count, 1)

    def test_overrun_count_accumulates(self):
        """Overrun counter increments each time an overrun occurs."""
        harness = _OverrunHarness()
        period = RobotConstants.kPeriodicPeriodSec

        for _ in range(3):
            wpilib.simulation.stepTiming(period * 2)
            harness.robotPeriodic()

        self.assertEqual(harness.overrun_count, 3)

    def test_overrun_clears_after_good_loop(self):
        """Alert clears when a loop completes within the period."""
        harness = _OverrunHarness()
        period = RobotConstants.kPeriodicPeriodSec

        # Trigger an overrun
        wpilib.simulation.stepTiming(period * 2)
        harness.robotPeriodic()
        self.assertEqual(harness.overrun_count, 1)

        # Next loop is fast
        wpilib.simulation.stepTiming(period * 0.5)
        harness.robotPeriodic()

        # Count stays at 1 (no new overrun)
        self.assertEqual(harness.overrun_count, 1)


if __name__ == "__main__":
    unittest.main()
