"""Motivational quotes from sci-fi, fantasy, and zombie/post-apocalyptic sources."""

import random

QUOTES = [
    # Sci-fi
    ("The needs of the many outweigh the needs of the few.",
     "Mr. Spock — Star Trek II: The Wrath of Khan"),
    ("Do. Or do not. There is no try.",
     "Yoda — The Empire Strikes Back"),
    ("I find your lack of faith disturbing.",
     "Darth Vader — Star Wars: A New Hope"),
    ("Fear is the mind-killer.",
     "Frank Herbert — Dune"),
    ("I must not fear. Fear is the mind-killer. Fear is the little-death that "
     "brings total obliteration.",
     "Paul Atreides — Dune"),
    ("A person is smart. People are dumb, panicky, dangerous animals.",
     "Agent K — Men in Black"),
    ("In the beginning, the Universe was created. This has made a lot of people "
     "very angry and been widely regarded as a bad move.",
     "Douglas Adams — The Hitchhiker's Guide to the Galaxy"),
    ("Don't Panic.",
     "Douglas Adams — The Hitchhiker's Guide to the Galaxy"),
    ("So long, and thanks for all the fish.",
     "Douglas Adams — The Hitchhiker's Guide to the Galaxy"),
    ("I am putting myself to the fullest possible use, which is all I think that "
     "any conscious entity can ever hope to do.",
     "HAL 9000 — 2001: A Space Odyssey"),
    ("Open the pod bay doors, HAL.",
     "Dave Bowman — 2001: A Space Odyssey"),
    ("Never tell me the odds.",
     "Han Solo — The Empire Strikes Back"),
    ("It's a trap!",
     "Admiral Ackbar — Return of the Jedi"),
    ("With great power comes great responsibility.",
     "Uncle Ben — Spider-Man"),
    ("Why do we fall? So we can learn to pick ourselves up.",
     "Thomas Wayne — Batman Begins"),
    ("You either die a hero, or you live long enough to see yourself become "
     "the villain.",
     "Harvey Dent — The Dark Knight"),
    ("It is not our abilities that show what we truly are. It is our choices.",
     "Albus Dumbledore — Harry Potter and the Chamber of Secrets"),
    ("It does not do to dwell on dreams and forget to live.",
     "Albus Dumbledore — Harry Potter and the Sorcerer's Stone"),
    ("Happiness can be found even in the darkest of times, if one only remembers "
     "to turn on the light.",
     "Albus Dumbledore — Harry Potter and the Prisoner of Azkaban"),
    ("The Force will be with you. Always.",
     "Obi-Wan Kenobi — Star Wars: A New Hope"),
    ("I am your father.",
     "Darth Vader — The Empire Strikes Back"),
    ("We are Groot.",
     "Groot — Guardians of the Galaxy"),
    ("Just keep swimming.",
     "Dory — Finding Nemo"),
    ("To infinity and beyond!",
     "Buzz Lightyear — Toy Story"),
    ("Adventure is out there!",
     "Ellie — Up"),
    ("The stuff that dreams are made of.",
     "Sam Spade — The Maltese Falcon"),
    ("I'll be back.",
     "The Terminator — The Terminator"),
    ("Come with me if you want to live.",
     "Kyle Reese — The Terminator"),
    ("Hasta la vista, baby.",
     "The Terminator — Terminator 2: Judgment Day"),
    ("Get to the chopper!",
     "Dutch — Predator"),
    ("In space, no one can hear you scream.",
     "Tagline — Alien"),
    ("Game over, man. Game over!",
     "Hudson — Aliens"),
    ("Get away from her, you bitch!",
     "Ripley — Aliens"),
    ("You're gonna need a bigger boat.",
     "Martin Brody — Jaws"),
    ("Life finds a way.",
     "Ian Malcolm — Jurassic Park"),
    ("Your scientists were so preoccupied with whether or not they could, they "
     "didn't stop to think if they should.",
     "Ian Malcolm — Jurassic Park"),
    ("Clever girl.",
     "Muldoon — Jurassic Park"),
    ("Hold on to your butts.",
     "Ray Arnold — Jurassic Park"),
    ("I am Groot.",
     "Groot — Guardians of the Galaxy"),
    ("Wakanda forever.",
     "Various — Black Panther"),
    ("I am Iron Man.",
     "Tony Stark — Avengers: Endgame"),
    ("Part of the journey is the end.",
     "Tony Stark — Avengers: Endgame"),
    ("Whatever it takes.",
     "The Avengers — Avengers: Endgame"),
    ("We're in the endgame now.",
     "Doctor Strange — Avengers: Infinity War"),
    ("I went forward in time... to view alternate futures. To see all the "
     "possible outcomes of the coming conflict.",
     "Doctor Strange — Avengers: Infinity War"),
    ("Dread it. Run from it. Destiny still arrives.",
     "Thanos — Avengers: Infinity War"),
    ("Reality is often disappointing.",
     "Thanos — Avengers: Infinity War"),

    # Fantasy
    ("Not all those who wander are lost.",
     "J.R.R. Tolkien — The Fellowship of the Ring"),
    ("All we have to decide is what to do with the time that is given us.",
     "Gandalf — The Fellowship of the Ring"),
    ("One does not simply walk into Mordor.",
     "Boromir — The Fellowship of the Ring"),
    ("Even the smallest person can change the course of the future.",
     "Galadriel — The Fellowship of the Ring"),
    ("Fly, you fools!",
     "Gandalf — The Fellowship of the Ring"),
    ("You shall not pass!",
     "Gandalf — The Fellowship of the Ring"),
    ("My precious.",
     "Gollum — The Lord of the Rings"),
    ("I can't carry it for you, but I can carry you!",
     "Samwise Gamgee — The Return of the King"),
    ("There's some good in this world, Mr. Frodo, and it's worth fighting for.",
     "Samwise Gamgee — The Two Towers"),
    ("A wizard is never late, nor is he early. He arrives precisely when he "
     "means to.",
     "Gandalf — The Fellowship of the Ring"),
    ("Courage is found in unlikely places.",
     "J.R.R. Tolkien — The Fellowship of the Ring"),
    ("I am no man.",
     "Éowyn — The Return of the King"),
    ("When in doubt, follow your nose.",
     "Gandalf — The Fellowship of the Ring"),
    ("May it be a light to you in dark places, when all other lights go out.",
     "Galadriel — The Fellowship of the Ring"),
    ("Winter is coming.",
     "House Stark — Game of Thrones"),
    ("A Lannister always pays his debts.",
     "House Lannister words — Game of Thrones"),
    ("What is dead may never die.",
     "House Greyjoy words — Game of Thrones"),
    ("Valar morghulis.",
     "Old Valyrian — Game of Thrones"),
    ("The night is dark and full of terrors.",
     "Melisandre — Game of Thrones"),
    ("Chaos isn't a pit. Chaos is a ladder.",
     "Littlefinger — Game of Thrones"),
    ("When you play the game of thrones, you win or you die.",
     "Cersei Lannister — Game of Thrones"),
    ("Power resides where men believe it resides.",
     "Varys — Game of Thrones"),
    ("There is only one god and His name is Death, and there is only one thing "
     "we say to Death: Not today.",
     "Syrio Forel — Game of Thrones"),
    ("A mind needs books as a sword needs a whetstone, if it is to keep its edge.",
     "Tyrion Lannister — Game of Thrones"),
    ("I drink and I know things.",
     "Tyrion Lannister — Game of Thrones"),
    ("Hold the door.",
     "Hodor — Game of Thrones"),
    ("The things I do for love.",
     "Jaime Lannister — Game of Thrones"),

    # Zombie / Post-Apocalyptic
    ("When there is no more room in hell, the dead will walk the earth.",
     "Peter — Dawn of the Dead"),
    ("Rule #1: Cardio.",
     "Columbus — Zombieland"),
    ("Rule #2: The Double Tap.",
     "Columbus — Zombieland"),
    ("Rule #32: Enjoy the little things.",
     "Columbus — Zombieland"),
    ("This is the United States of Zombieland.",
     "Columbus — Zombieland"),
    ("Time to nut up or shut up.",
     "Tallahassee — Zombieland"),
    ("It's the end of the world. Have a drink.",
     "Tallahassee — Zombieland"),
    ("We're all infected.",
     "Jenner — The Walking Dead"),
    ("You kill or you die. Or you die and you kill.",
     "The Governor — The Walking Dead"),
    ("Just because we're good people doesn't mean we won't kill you.",
     "Rick Grimes — The Walking Dead"),
    ("We are the walking dead.",
     "Rick Grimes — The Walking Dead"),
    ("Stuff and thangs.",
     "Rick Grimes — The Walking Dead"),
    ("Coral!",
     "Rick Grimes — The Walking Dead"),
    ("I'm going to kill you. Not today, not tomorrow... but I'm going to kill you.",
     "Rick Grimes — The Walking Dead"),
    ("You don't know what it's like out there. You may think you do but you don't.",
     "Rick Grimes — The Walking Dead"),
    ("The world doesn't end. It just becomes something different.",
     "Unknown — Post-Apocalyptic Wisdom"),
    ("Civilization is just the slow process of learning to be kind.",
     "Will Durant — paraphrased in countless post-apocalyptic narratives"),
    ("In every age, in every place, the deeds of men remain the same.",
     "Berserk — Kentaro Miura"),
    ("Struggle. That's all there is.",
     "Guts — Berserk"),
    ("Even if we forget the faces of our friends, we will never forget the bonds "
     "that were carved into our souls.",
     "Naruto Uzumaki — Naruto"),
    ("I never go back on my word. That's my ninja way!",
     "Naruto Uzumaki — Naruto"),
    ("The only ones who should kill are those who are prepared to be killed.",
     "Lelouch vi Britannia — Code Geass"),
    ("If you don't take risks, you can't create a future.",
     "Monkey D. Luffy — One Piece"),
    ("I'm going to be King of the Pirates!",
     "Monkey D. Luffy — One Piece"),
    ("A scar is proof that you survived.",
     "Unknown"),
    ("The measure of a warrior is not how hard they hit, but how hard they can "
     "get hit and keep moving forward.",
     "Rocky Balboa — Rocky Balboa"),
    ("It ain't about how hard you hit. It's about how hard you can get hit and "
     "keep moving forward.",
     "Rocky Balboa — Rocky Balboa"),
    ("Every passing minute is another chance to turn it all around.",
     "Sofia — Vanilla Sky"),
    ("Hope is a good thing, maybe the best of things, and no good thing ever dies.",
     "Andy Dufresne — The Shawshank Redemption"),
    ("Get busy living, or get busy dying.",
     "Andy Dufresne — The Shawshank Redemption"),
    ("Fear can hold you prisoner. Hope can set you free.",
     "Tagline — The Shawshank Redemption"),
]


def get_quote() -> tuple[str, str]:
    """Return a random (quote, attribution) tuple."""
    return random.choice(QUOTES)


def format_quote() -> str:
    """Return a formatted quote string ready for Discord."""
    text, attribution = get_quote()
    return f'*"{text}"*\n— {attribution}'
