"""
Tests for camera visualizer route modules and field cache.

These test the Python route logic directly without starting an HTTP server.
Run with: pytest host/camera_visualizer/tests/ -v

Generated by Claude.
"""

import json
import os
import tempfile
import zipfile

import pytest

# Ensure project root is on path
import sys
sys.path.insert(0, os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..', '..')
))

from host.camera_visualizer.routes import config, fields, cad, points
from host.camera_visualizer.field_cache import FieldCache, FIELD_LIST


# ── Config routes ─────────────────────────────────────────────────────

class TestConfigRoutes:
    def test_config_json_has_required_keys(self):
        cfg = json.loads(config.build_config_json())
        assert 'robot_frame' in cfg
        assert 'cameras' in cfg
        assert 'mechanisms' in cfg

    def test_robot_frame_has_dimensions(self):
        cfg = json.loads(config.build_config_json())
        frame = cfg['robot_frame']
        assert 'width_inches' in frame
        assert 'length_inches' in frame
        assert 'width_meters' in frame
        assert 'length_meters' in frame
        assert frame['width_meters'] > 0
        assert frame['length_meters'] > 0

    def test_cameras_have_required_fields(self):
        cfg = json.loads(config.build_config_json())
        for cam in cfg['cameras']:
            for key in ['name', 'x_inches', 'y_inches', 'z_inches',
                        'yaw_deg', 'pitch_deg', 'fov_deg']:
                assert key in cam, f"Missing '{key}' in camera {cam.get('name')}"

    def test_mechanisms_have_required_fields(self):
        cfg = json.loads(config.build_config_json())
        for mech in cfg['mechanisms']:
            for key in ['name', 'type', 'x_meters', 'y_meters', 'z_meters']:
                assert key in mech, f"Missing '{key}' in mechanism {mech.get('name')}"

    def test_build_page_injects_config(self):
        here = os.path.join(
            os.path.dirname(__file__), '..'
        )
        page = config.build_page(here)
        assert b'window.__ROBOT_CONFIG__' in page
        assert b'robot_frame' in page
        assert b'<html' in page


# ── Field tag routes ──────────────────────────────────────────────────

class TestFieldTagRoutes:
    def test_field_tags_returns_tags(self):
        result = fields.get_field_tags()
        assert 'tags' in result
        assert len(result['tags']) > 0

    def test_field_tags_have_positions(self):
        result = fields.get_field_tags()
        for tag in result['tags']:
            assert 'id' in tag
            assert 'x' in tag
            assert 'y' in tag
            assert 'z' in tag
            assert isinstance(tag['id'], int)
            assert tag['z'] > 0  # all tags are above ground

    def test_field_tags_have_rotations(self):
        result = fields.get_field_tags()
        for tag in result['tags']:
            assert 'yaw_deg' in tag

    def test_field_dimensions(self):
        result = fields.get_field_tags()
        assert 'field_length' in result
        assert 'field_width' in result
        # Standard FRC field is ~16.5m x ~8m
        assert 15 < result['field_length'] < 18
        assert 7 < result['field_width'] < 9

    def test_tag_count_2026(self):
        """2026 field should have 32 tags."""
        result = fields.get_field_tags()
        assert len(result['tags']) == 32


# ── CAD routes ────────────────────────────────────────────────────────

class TestCadRoutes:
    def test_list_cad_models_with_real_dir(self):
        cad_dir = os.path.join(
            os.path.dirname(__file__), '..', '..', '..', 'cad'
        )
        models = cad.list_cad_models(cad_dir)
        # May or may not have models, but should be a list
        assert isinstance(models, list)
        for m in models:
            assert 'name' in m
            assert 'url' in m
            assert 'size' in m

    def test_list_cad_models_empty_dir(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            models = cad.list_cad_models(tmpdir)
            assert models == []

    def test_list_cad_models_nonexistent_dir(self):
        models = cad.list_cad_models('/nonexistent/path')
        assert models == []

    def test_serve_cad_file_rejects_bad_extension(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            # Create a .py file that should be rejected
            with open(os.path.join(tmpdir, 'evil.py'), 'w') as f:
                f.write('import os')
            data, mime = cad.serve_cad_file(tmpdir, 'evil.py')
            assert data is None

    def test_serve_cad_file_rejects_path_traversal(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            data, mime = cad.serve_cad_file(tmpdir, '../../../etc/passwd')
            assert data is None

    def test_serve_cad_file_missing(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            data, mime = cad.serve_cad_file(tmpdir, 'nonexistent.glb')
            assert data is None

    def test_serve_cad_file_glb(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            test_data = b'\x00\x01\x02\x03'
            with open(os.path.join(tmpdir, 'test.glb'), 'wb') as f:
                f.write(test_data)
            data, mime = cad.serve_cad_file(tmpdir, 'test.glb')
            assert data == test_data
            assert mime == 'model/gltf-binary'

    def test_serve_cad_file_gltf(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            test_data = b'{"asset":{}}'
            with open(os.path.join(tmpdir, 'test.gltf'), 'wb') as f:
                f.write(test_data)
            data, mime = cad.serve_cad_file(tmpdir, 'test.gltf')
            assert data == test_data
            assert mime == 'model/gltf+json'


# ── Points routes ─────────────────────────────────────────────────────

class TestPointRoutes:
    def test_load_points_empty(self):
        result = points.load_points('/nonexistent/file.json')
        assert json.loads(result) == {"points": []}

    def test_save_and_load_roundtrip(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            fpath = os.path.join(tmpdir, 'sub', 'points.json')
            test_data = {"points": [
                {"id": 1, "name": "test", "x": 1.5, "y": 2.5, "z": 0.5}
            ]}
            points.save_points(fpath, json.dumps(test_data).encode())
            loaded = json.loads(points.load_points(fpath))
            assert loaded == test_data

    def test_save_creates_directories(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            fpath = os.path.join(tmpdir, 'a', 'b', 'c', 'points.json')
            points.save_points(fpath, b'{}')
            assert os.path.isfile(fpath)


# ── Field cache ───────────────────────────────────────────────────────

class TestFieldCache:
    def test_field_list_not_empty(self):
        cache = FieldCache('/tmp/test')
        fields = cache.get_field_list()
        assert len(fields) >= 4

    def test_field_list_has_robot_view(self):
        cache = FieldCache('/tmp/test')
        ids = [f['id'] for f in cache.get_field_list()]
        assert 'robot-view' in ids

    def test_field_list_has_2026(self):
        cache = FieldCache('/tmp/test')
        ids = [f['id'] for f in cache.get_field_list()]
        assert '2026-field' in ids

    def test_field_list_has_cat_box(self):
        cache = FieldCache('/tmp/test')
        ids = [f['id'] for f in cache.get_field_list()]
        assert 'cat-box' in ids

    def test_get_field_info_valid(self):
        cache = FieldCache('/tmp/test')
        info = cache.get_field_info('2026-field')
        assert info is not None
        assert info['name'] == '2026 Field'
        assert 'zipEntry' in info

    def test_get_field_info_invalid(self):
        cache = FieldCache('/tmp/test')
        assert cache.get_field_info('nonexistent') is None

    def test_extract_builtin_returns_none(self):
        """Builtin scenes (robot-view, cat-box) have no zip entry."""
        cache = FieldCache('/tmp/test')
        config, glb = cache.extract_field('robot-view')
        assert config is None
        assert glb is None

    def test_extract_field_from_test_bundle(self):
        """Create a minimal test bundle and verify extraction."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = os.path.join(tmpdir, 'fields')
            bundle_path = os.path.join(tmpdir, 'bundle.zip')

            # Build a fake inner zip with config.json and model.glb
            inner_buf = _make_test_field_zip(
                config={"name": "Test Field", "widthInches": 651},
                glb_data=b'fake-glb-data',
            )

            # Build outer bundle containing the inner zip
            with zipfile.ZipFile(bundle_path, 'w') as outer:
                outer.writestr('Field3d_2026FRCFieldV1.zip', inner_buf)

            cache = FieldCache(cache_dir, bundle_path)
            cfg, glb = cache.extract_field('2026-field')

            assert cfg is not None
            assert cfg['name'] == 'Test Field'
            assert glb == b'fake-glb-data'

    def test_extract_field_caches_locally(self):
        """Second extraction should read from local cache, not bundle."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = os.path.join(tmpdir, 'fields')
            bundle_path = os.path.join(tmpdir, 'bundle.zip')

            inner_buf = _make_test_field_zip(
                config={"name": "Cached"},
                glb_data=b'glb-bytes',
            )
            with zipfile.ZipFile(bundle_path, 'w') as outer:
                outer.writestr('Field3d_2026FRCFieldV1.zip', inner_buf)

            cache = FieldCache(cache_dir, bundle_path)
            cache.extract_field('2026-field')

            # Delete the bundle — cache should still work
            os.remove(bundle_path)

            cfg, glb = cache.extract_field('2026-field')
            assert cfg['name'] == 'Cached'
            assert glb == b'glb-bytes'


def _make_test_field_zip(config: dict, glb_data: bytes) -> bytes:
    """Create a minimal field zip (config.json + model.glb) in memory."""
    import io
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as z:
        z.writestr('config.json', json.dumps(config))
        z.writestr('model.glb', glb_data)
    return buf.getvalue()
