"""Tests for chart_generator module. — Generated by Claude"""

from host.match_monitor.chart_generator import _build_mode_spans, _find_last_match_block


class TestBuildModeSpans:
    """Test mode span building from transitions."""

    def test_empty_transitions(self):
        spans = _build_mode_spans([], 100.0)
        assert spans == [(0, 100.0, 'disabled')]

    def test_simple_auto_teleop(self):
        """Standard FRC match: disabled → auto → teleop → disabled."""
        transitions = [
            {'time_sec': 0.0, 'mode': 'autonomous', 'value': True},
            {'time_sec': 0.0, 'mode': 'enabled', 'value': True},
            {'time_sec': 15.0, 'mode': 'autonomous', 'value': False},
            # enabled stays True → teleop
            {'time_sec': 135.0, 'mode': 'enabled', 'value': False},
        ]
        spans = _build_mode_spans(transitions, 150.0)
        assert spans == [
            (0.0, 15.0, 'autonomous'),
            (15.0, 135.0, 'teleop'),
            (135.0, 150.0, 'disabled'),
        ]

    def test_bench_session_multiple_cycles(self):
        """Multiple enable/disable cycles like the real log data."""
        transitions = [
            # Cycle 1: test mode 5-8s
            {'time_sec': 0.0, 'mode': 'enabled', 'value': False},
            {'time_sec': 0.0, 'mode': 'autonomous', 'value': False},
            {'time_sec': 0.0, 'mode': 'test', 'value': True},
            {'time_sec': 5.0, 'mode': 'enabled', 'value': True},
            {'time_sec': 8.0, 'mode': 'enabled', 'value': False},
            # Cycle 2: test mode 212-216s
            {'time_sec': 212.0, 'mode': 'enabled', 'value': True},
            {'time_sec': 216.0, 'mode': 'enabled', 'value': False},
            # Cycle 3: auto+teleop 563-602s
            {'time_sec': 545.0, 'mode': 'autonomous', 'value': True},
            {'time_sec': 545.0, 'mode': 'test', 'value': False},
            {'time_sec': 563.0, 'mode': 'enabled', 'value': True},
            {'time_sec': 573.0, 'mode': 'enabled', 'value': False},
            {'time_sec': 574.0, 'mode': 'autonomous', 'value': False},
            {'time_sec': 575.0, 'mode': 'enabled', 'value': True},
            {'time_sec': 602.0, 'mode': 'enabled', 'value': False},
        ]
        spans = _build_mode_spans(transitions, 625.0)

        # Should have disabled gaps between cycles
        modes = [(round(s, 1), round(e, 1), m) for s, e, m in spans]
        # Check the last block: auto 563-573, disabled 573-575, teleop 575-602
        assert (563.0, 573.0, 'autonomous') in modes
        assert (575.0, 602.0, 'teleop') in modes
        # Large disabled gaps between cycles
        assert (8.0, 212.0, 'disabled') in modes
        # autonomous=True at 545 doesn't change mode (enabled is still False)
        # so disabled extends to 563 when enabled goes True
        assert (216.0, 563.0, 'disabled') in modes

    def test_old_format_no_value_key(self):
        """Backward compat: transitions without 'value' key default to True."""
        transitions = [
            {'time_sec': 5.0, 'mode': 'enabled'},
            {'time_sec': 5.0, 'mode': 'autonomous'},
        ]
        spans = _build_mode_spans(transitions, 30.0)
        assert spans[0] == (0, 5.0, 'disabled')
        assert spans[1][2] == 'autonomous'


class TestFindLastMatchBlock:
    """Test finding the last contiguous match block from spans."""

    def test_single_match(self):
        """Simple auto→teleop→disabled."""
        spans = [
            (0, 15.0, 'autonomous'),
            (15.0, 135.0, 'teleop'),
            (135.0, 150.0, 'disabled'),
        ]
        t_zero, match_end = _find_last_match_block(spans)
        assert t_zero == 0.0  # first auto/teleop
        assert match_end == 135.0

    def test_bench_session_isolates_last_cycle(self):
        """Multiple enable cycles — should only pick the last one.

        Real data from bench test:
          test 5-8, disabled 8-212, test 212-216, disabled 216-404,
          test 404-408, disabled 408-563, auto 563-573, disabled 573-575,
          teleop 575-602, disabled 602-625
        """
        spans = [
            (0.0, 5.0, 'disabled'),
            (5.0, 8.0, 'test'),
            (8.0, 212.0, 'disabled'),
            (212.0, 216.0, 'test'),
            (216.0, 404.0, 'disabled'),
            (404.0, 408.0, 'test'),
            (408.0, 563.0, 'disabled'),
            (563.0, 573.0, 'autonomous'),
            (573.0, 575.0, 'disabled'),     # 2s gap — should bridge
            (575.0, 602.0, 'teleop'),
            (602.0, 625.0, 'disabled'),
        ]
        t_zero, match_end = _find_last_match_block(spans)
        assert t_zero == 563.0   # first auto in last block
        assert match_end == 602.0

    def test_small_gap_bridged(self):
        """Disabled gap < 5s between auto and teleop should be bridged."""
        spans = [
            (0.0, 10.0, 'disabled'),
            (10.0, 25.0, 'autonomous'),
            (25.0, 28.0, 'disabled'),   # 3s gap
            (28.0, 150.0, 'teleop'),
            (150.0, 160.0, 'disabled'),
        ]
        t_zero, match_end = _find_last_match_block(spans)
        assert t_zero == 10.0
        assert match_end == 150.0

    def test_large_gap_splits(self):
        """Disabled gap > 5s should split into separate matches."""
        spans = [
            (0.0, 10.0, 'disabled'),
            (10.0, 20.0, 'teleop'),
            (20.0, 100.0, 'disabled'),   # 80s gap
            (100.0, 130.0, 'teleop'),
            (130.0, 140.0, 'disabled'),
        ]
        t_zero, match_end = _find_last_match_block(spans)
        assert t_zero == 100.0
        assert match_end == 130.0

    def test_all_disabled(self):
        """No active spans — returns defaults."""
        spans = [
            (0.0, 100.0, 'disabled'),
        ]
        t_zero, match_end = _find_last_match_block(spans)
        assert t_zero == 0.0
        assert match_end == 100.0  # duration fallback
